extends RefCounted


const EN: Dictionary = {
	# Authored surfaces for stable lexemes. These are not generated substitutions.
	"隐藏楼层": "hidden level",
	"未登记空间": "unregistered space",
	"不许去的楼上": "the upstairs we must not visit",
	"末班电梯账号": "last-elevator account",
	"反复梦见电梯的患者": "the patient who repeatedly dreams of an elevator",
	"回家的电梯": "the elevator home",
	"停在": "stops at",
	"定位到": "checks in at",
	"持续停留于": "remains fixed at",
	"等在": "waits at",
	"无信号的短信": "a message without signal",
	"离线消息": "offline message",
	"无来源记录": "record without a source",
	"没有声音的纸条": "the silent note",
	"明天的我": "tomorrow's me",
	"未来账号": "future account",
	"预期自我": "anticipated self",
	"明天醒来的你": "you when you wake tomorrow",
	"发来": "sends",
	"推送": "pushes",
	"投射出": "projects",
	"塞给我": "slips me",
	"一扇亮窗": "a lit window",
	"在线窗口": "online window",
	"视觉对象": "visual object",
	"会眨眼的窗": "the blinking window",
	"消失在": "disappears at",
	"下线于": "goes offline at",
	"从知觉中脱落于": "drops out of perception at",
	"躲进": "hides inside",
	"塔下频道": "tower-base channel",
	"固定场景": "fixed scene",
	"我们楼下": "downstairs from us",
	"一颗月亮": "one moon",
	"第二个月亮": "a second moon",
	"重复圆形": "repeated circular form",
	"小月亮": "little moon",
	"多出": "appears in excess of",
	"自动生成": "auto-generates",
	"发生复视": "produces double vision of",
	"偷偷长出": "secretly grows",
	"昨夜影像": "last night's image",
	"患者图像记录": "the patient's image record",
	"你藏起来的照片": "the photo you hid",
	"末班路线": "last service route",
	"反复交通意象": "recurring transit image",
	"接我们回家的车": "the bus that takes us home",
	"没有抵达": "does not reach",
	"未刷新到": "fails to refresh to",
	"无法到达": "cannot arrive at",
	"忘了停在": "forgets to stop at",
	"终点": "the terminus",
	"最终页面": "final page",
	"结束条件": "termination condition",
	"家的门口": "our front door",
	"废站广播": "abandoned-station broadcast",
	"离线广播": "offline broadcast",
	"听觉内容": "auditory content",
	"墙里的喇叭": "the speaker in the wall",
	"喊出": "calls out",
	"公开了": "publishes",
	"重复呼唤": "repeatedly calls",
	"学会了": "learns",
	"我的名字": "my name",
	"用户实名": "verified user name",
	"自我称呼": "self-designation",
	"我给你的名字": "the name I gave you",
	"封闭站台": "sealed platform",
	"停用站点": "decommissioned stop",
	"封闭场景": "enclosed scene",
	"没人等车的地方": "the place where nobody waits",
	"重新亮起": "lights again",
	"恢复在线": "comes back online",
	"再次显现": "manifests again",
	"又睁开": "opens its eyes again",
	"十年前的灯": "a light from ten years ago",
	"过期指示灯": "expired indicator light",
	"陈旧光源记忆": "memory of an old light source",
	"你忘掉的小灯": "the little light you forgot",
	"便利店员": "convenience-store clerk",
	"夜班账号": "night-shift account",
	"无面孔人物": "faceless figure",
	"替我们看门的人": "the one who watches our door",
	"没有留下": "leaves no",
	"删除了": "deletes",
	"未形成": "fails to form",
	"不肯带走": "refuses to take",
	"影子": "shadow",
	"在线痕迹": "online trace",
	"自体投影": "self-projection",
	"脚下的黑朋友": "the dark friend under your feet",
	"预约推送": "scheduled post",
	"预期记录": "anticipated record",
	"明天塞进门缝的纸": "the paper slipped under the door tomorrow",
	"写着": "says",
	"标记为": "labels as",
	"诊断为": "diagnoses as",
	"偷偷叫作": "secretly calls",
	"我的失踪": "my disappearance",
	"用户离线": "user offline",
	"对象缺席": "subject absent",
	"你不回家": "you not coming home",
	"历史缓存": "history cache",
	"既往记录": "prior record",
	"以前写给你的信": "the letter I wrote you before",
	"回复了": "replies to",
	"重新推送": "reposts",
	"回返为": "returns as",
	"开口叫了": "calls aloud to",
	"当前账号": "current account",
	"现时自我": "present self",
	"现在陪我的你": "you who are with me now",
	"地图": "map",
	"导航服务": "navigation service",
	"空间图式": "spatial schema",
	"你画的路线": "the route you drew",
	"删掉": "deletes",
	"隐藏": "conceals",
	"压抑": "represses",
	"擦掉": "erases",
	"返程路线": "return route",
	"退行路径": "regressive path",
	"回到我这里的路": "the road back to me",
	"门禁系统": "entry system",
	"行为记录": "behavioral record",
	"门口那只眼睛": "the eye at the door",
	"判定异常": "flags as abnormal",
	"否定": "denies",
	"假装没看见": "pretends not to see",
	"我在屋里": "I am inside",
	"用户已在家": "user already home",
	"对象仍在场": "subject still present",
	"你一直陪着我": "you have always stayed with me",

	# Tutorial, notebook, doctor composer, and explicit debug assistance.
	"把发布过的词重新说给医生": "Say the published words to the doctor again",
	"同一个词到了这里会换一种说法。拖拽词块，或先点词块再点句槽。": "The same word is spoken differently here. Drag a word, or select it and then choose a sentence slot.",
	"对医生说出口": "Say It to the Doctor",
	"缝线布偶 / GUIDE": "STITCHED DOLL / GUIDE",
	"你已经会自己走了。至少现在是。": "You can walk on your own now. At least for the moment.",
	"测试提示：继续探索。": "TEST: Continue exploring.",
	"已答对": "correct",
	"未完成": "incomplete",
	"已拾取": "collected",
	"已显形": "revealed",
	"未显形": "hidden",
	"本层测试：关键 NPC %s / 前置物 %s": "LEVEL TEST: key NPC %s / prerequisite %s",
	"目标：%s。%s": "TARGET: %s. %s",
	"前置物": "prerequisite",
	"跟随荧光测试标记。": "Follow the fluorescent test marker.",
	"隐藏层测试：前置物 %d/3 · 污染 %d/80 · 第三层结束检查": "HIDDEN-LEVEL TEST: prerequisites %d/3 · corruption %d/80 · checked at the end of Level 3",
	"污染 %d%%  /  发布与现实表达会推进污染": "CORRUPTION %d%%  /  Publishing and speaking in reality increase corruption",
	"拾取字词不增加污染；使用它才会改变语言。": "Collecting words does not add corruption; using them changes language.",
	"今天没有可拾取的词": "No words can be collected today",
	"完整句子": "Complete Sentence",
	"从帖子拾取原词，再按语法位置组成手机世界会使用的句子。": "Collect original words from posts, then arrange them into a sentence the phone world can use.",
	"确认组成句子": "Confirm Sentence",
	"拾取词库": "Collected Words",
	"词": "word",
	"对象": "subject",
	"动作": "action",
	"去向": "object",
	"句子结构": "Sentence Structure",
	"手机语言预览：%s": "Phone-language preview: %s",
	"%s：%s": "%s: %s",
	"你说：%s": "You said: %s",
	"理解度：%d%%": "Understanding: %d%%",
	"还没有能带到医生面前的词。先在手机里发布一句完整的话。": "No words can be brought to the doctor yet. First publish a complete sentence on the phone.",
	"原词：%s": "Original: %s",
	"手机里：%s": "On the phone: %s",
	"等待词语": "waiting for a word",
	"原句：%s": "Original sentence: %s",
	"医生语言：%s": "Doctor language: %s",
	"句子尚未完整。需要对象、动作和去向。": "The sentence is incomplete. It needs a subject, action, and object.",
	"第一层": "LEVEL 1",
	"选中了一个带到医生面前的词。": "Selected a word to bring to the doctor.",
	"词已经进入医生句槽。": "The word entered the doctor's sentence slot.",
	"这个词不能放在句子的这个位置。": "That word cannot occupy this sentence position.",
	"先选择一个词。": "Select a word first.",
	"同一句话到了医生那里，已经不是原来的样子。": "The same sentence is no longer itself when it reaches the doctor.",
	"句子还不完整，或者这些词还没有在手机里发布。": "The sentence is incomplete, or these words have not been published on the phone.",
	"完整句子已经写好：%s": "Complete sentence written: %s",
	"需要分别填入对象、动作和去向。": "Fill the subject, action, and object separately.",
	"等待对象、动作和去向": "Waiting for subject, action, and object",
	"谁 / 什么": "who / what",
	"放入主语": "place subject",
	"发生了什么": "what happened",
	"放入动作": "place action",
	"对谁 / 在哪里": "to whom / where",
	"放入落点": "place object",

	# Doctor lines, debug markers, and state feedback.
	"把你刚才放进手机的句子再说一遍。不要替它解释。": "Repeat the sentence you just put into the phone. Do not explain it.",
	"医生记下的句子和你记得的并不相同。": "The sentence the doctor writes is not the one you remember.",
	"你从屏幕里带回了哪些词？按你认为原本的顺序说。": "Which words did you bring back from the screen? Say them in the order you think was original.",
	"医生在每个词旁边写下另一种用途。": "The doctor writes another use beside each word.",
	"请只使用仍属于你的词，描述你现在在哪里。": "Use only the words that still belong to you and describe where you are.",
	"医生停笔。病历上的主语比你先消失。": "The doctor stops writing. The subject in the chart disappears before you do.",
	"这些词没有来源。你还坚持它们是你选的吗？": "These words have no source. Do you still insist that you chose them?",
	"没有人替这句话登记说话者。": "No speaker was registered for this sentence.",
	"我会先念完屏幕教我的那句，然后说明路口为什么没有放我过去。": "I will finish the sentence the screen taught me, then explain why the crossing would not let me pass.",
	"我们不再问你叫什么。我们只核对手机替你说过哪一句话。": "We no longer ask your name. We only verify which sentence the phone spoke for you.",
	"无名信徒在听见屏幕用词时微笑，在听见其余内容时闭上眼睛。": "The unnamed believer smiles at the screen's words and closes their eyes for everything else.",
	"那句话跟着我，但我的名字仍然应该先于它出现。": "That sentence follows me, but my name should still appear before it.",
	"出示旧句": "Show the old sentence",
	"我们顺着屏幕留下的标记走，看看旧句子把终点改到了哪里。": "We follow the marks left by the screen and see where the old sentence moved the terminus.",
	"旧句之后": "After the old sentence",
	"等它念完屏幕借来的话，我要在第一个属于今天的停顿下车。": "After it finishes the words borrowed from the screen, I will get off at the first pause that belongs to today.",
	"墙里的回声开始替我们回答，而且每次都比原话多一句屏幕里的旧话。要把哪一句留下？": "The echo in the wall answers for us, adding one old screen sentence each time. Which sentence stays?",
	"只留下我们刚才说的句子，旧话可以经过，但不要冒充回声。": "Keep only what we just said. Old words may pass through, but must not pretend to be the echo.",
	"标记旧话": "Mark the old words",
	"把多出来的旧话标上来源，让它不能假装今天才出生。": "Mark the extra old words with their source so they cannot pretend they were born today.",
	"档案柜要求给你的每句话填写“词语来源”。原创一栏已经被涂黑。你填什么？": "The archive asks for a word source on every sentence. The original column is blacked out. What do you enter?",
	"来自旧帖": "From an old post",
	"旧帖里的句子会自己寻找嗓子，圣歌只是它们同时借到人的时刻。": "Sentences in old posts seek their own throats. A hymn is only the moment they borrow people together.",
	"打开最早的一条，看看是谁先把未来误认成了旧记录。": "Open the earliest entry and see who first mistook the future for an old record.",
	"从三个词开始。先让它们组成一句完整的话，再看这句话到了另一个世界会变成什么。": "Begin with three words. Make a complete sentence, then see what it becomes in another world.",
	"所有被发布过的句子都说智者住在这里。这里没有智者。": "Every published sentence says the sage lives here. There is no sage here.",
	"最后一条回复只剩三个被划掉的词。帖子问：这句话原本是谁说的？": "Only three crossed-out words remain in the final reply. The post asks: who originally said this sentence?",
	"旧帖目击者没有截屏。三个词自行保存，却把说话者留成空白。": "The Old-Post Witness took no screenshot. The three words saved themselves, but left the speaker blank.",
	"第四层没有登记记录。": "LEVEL 4 has no registration record.",
	"你抵达了第 %d 层。": "You reached LEVEL %d.",
	"用你从屏幕里带回来的词说一句完整的话。": "Use the words brought back from the screen to say one complete sentence.",
	"医生把句子写了下来。": "The doctor writes the sentence down.",
	"句子「%s」": "Sentence: “%s”",
	"TEST  教程引导": "TEST  TUTORIAL GUIDE",
	"TEST  隐藏路线关键 NPC": "TEST  HIDDEN-ROUTE KEY NPC",
	"TEST  医生 / 语言拼句": "TEST  DOCTOR / SENTENCE PUZZLE",
	"TEST  前置物：%s": "TEST  PREREQUISITE: %s",
	"医生": "Doctor",
	"布偶把缝线朝向了下一步。": "The doll turns its seam toward the next step.",
	"布偶重复了一遍刚才的方向。": "The doll points in the same direction again.",
	"那一段话还没有长到你能听见的位置。": "That sentence has not grown close enough for you to hear it.",
	"它让你先照做，理由可以晚一点再问。": "It tells you to do it first. You may ask why later.",
	"缝线布偶指向了下一步。": "The stitched doll points to the next step.",
	"你把我放反了。缝口应该朝着路，不是朝着你。先拿起手机。帖子里有三种能拼成一句话的词。": "You put me down backward. The seam should face the road, not you. Pick up the phone. The posts contain three kinds of words that can form a sentence.",
	"布偶把一只纽扣眼转向手机。它没有催你，但路边的测试标记亮了。": "The doll turns one button eye toward the phone. It does not hurry you, but the roadside test marker lights up.",
	"先打开手机": "Open the phone first",
	"我先去看帖子。三个词，拼成一句完整的话。": "I will read the posts first. Three words, arranged into one complete sentence.",
	"先打开社交媒体，再打开任意一篇帖子。": "Open Social first, then open any post.",
	"为什么是三个": "Why three?",
	"为什么一定要三个词？少一个会发生什么？": "Why exactly three words? What happens if one is missing?",
	"对象、动作、去向。少一个，手机就会替你补。": "Subject, action, object. If one is missing, the phone fills it in for you.",
	"问词属于谁": "Ask who owns the words",
	"帖子里的词属于写下它的人，还是拾走它的人？": "Do the words belong to the person who wrote them, or the person who took them?",
	"先拾取。等你使用它时，再看它选择了谁。": "Collect them first. When you use them, see whom they choose.",
	"它又指向手机。三个词。对象、动作、去向。": "It points to the phone again. Three words. Subject, action, object.",
	"你把那句话发出去了。现在放下手机，去找医生。不要换词，只换说话的地方。": "You sent that sentence out. Now put down the phone and find the doctor. Do not change the words; change only where you speak them.",
	"布偶摸了摸右眼的纽扣。相同的三个词在里面排成了另一句话。": "The doll touches the button over its right eye. The same three words arrange themselves into another sentence inside it.",
	"去找医生": "Find the doctor",
	"我会用发布过的词，再说一次同样的句子。": "I will use the published words to say the same sentence again.",
	"医生就在这一层，荧光测试标记会指出位置。": "The doctor is on this level. The fluorescent test marker shows the location.",
	"问词为什么会变": "Ask why words change",
	"如果词没有换，为什么句子的意思会变？": "If the words did not change, why did the sentence's meaning change?",
	"因为手机和医生都坚持自己才是词的原主人。": "Because the phone and the doctor both insist they are the words' original owner.",
	"不替句子解释": "Do not explain for the sentence",
	"我只把词放进去，不替任何一个世界解释。": "I will only place the words. I will not explain for either world.",
	"很好。让两个版本并排留下。": "Good. Leave both versions side by side.",
	"它重复：发布过的词才能带到医生面前。": "It repeats: only published words can be brought to the doctor.",
	"这一层会检查你从下面带回来的东西。记录没有写数量，也没有写检查会在什么时候发生。": "This level will inspect what you brought from below. The record gives neither the quantity nor the time of inspection.",
	"布偶腹部的缝线自己松开一针。里面不是棉花，是一小段没有登记的楼梯声。": "One stitch on the doll's stomach comes loose. There is no stuffing inside, only a short sound of unregistered stairs.",
	"检查带回的东西": "Check what you brought back",
	"我会确认从下面带回来的东西都还在。": "I will make sure everything brought from below is still here.",
	"不要只数口袋。也要记住是谁告诉你去找它们。": "Do not count only your pockets. Remember who told you to find them.",
	"问检查的时机": "Ask when the inspection happens",
	"要到什么时候，这一层才会承认我已经准备好？": "When will this level admit that I am ready?",
	"等语言再也装不成干净的时候，出口才会做一次检查。": "The exit performs its inspection when language can no longer pretend to be clean.",
	"问不存在的楼层": "Ask about the level that does not exist",
	"如果还有下一层，为什么所有记录都只写到这里？": "If another level exists, why do all records stop here?",
	"因为那一层不是被锁住，而是没有被承认。": "Because that level is not locked. It is unacknowledged.",
	"它的腹部已经缝好。针脚数量和记录里的空格对不上。": "Its stomach is stitched shut again. The stitch count does not match the blanks in the record.",
	"用双手拇指与食指的四个指尖框出矩形区域，区域内会显示手机层。视频只在本机用于关键点计算，不写入存档。": "Frame a rectangle with both thumbs and index fingers. The phone layer appears inside it. Video is processed locally for landmarks and is never saved.",
	"等待双手四指框选": "Waiting for a four-fingertip frame",
	"已从系统摄像头编号 %d 收到画面。放下游戏内手机，用双手拇指与食指的四个指尖框出矩形。": "Video is arriving from system camera %d. Put down the in-game phone, then frame a rectangle with both thumbs and index fingers.",
}


const JA: Dictionary = {
	"隐藏楼层": "隠しレベル",
	"未登记空间": "未登録空間",
	"不许去的楼上": "行ってはいけない上の階",
	"末班电梯账号": "最終エレベーターのアカウント",
	"反复梦见电梯的患者": "エレベーターの夢を繰り返す患者",
	"回家的电梯": "家へ帰るエレベーター",
	"停在": "止まる",
	"定位到": "位置情報を付ける",
	"持续停留于": "滞留し続ける",
	"等在": "待っている",
	"无信号的短信": "圏外のメッセージ",
	"离线消息": "オフラインメッセージ",
	"无来源记录": "出典のない記録",
	"没有声音的纸条": "音のないメモ",
	"明天的我": "明日の私",
	"未来账号": "未来のアカウント",
	"预期自我": "予期された自己",
	"明天醒来的你": "明日目を覚ますあなた",
	"发来": "送ってくる",
	"推送": "配信する",
	"投射出": "投射する",
	"塞给我": "私に押しつける",
	"一扇亮窗": "明るい窓",
	"在线窗口": "オンラインの窓",
	"视觉对象": "視覚対象",
	"会眨眼的窗": "まばたきする窓",
	"消失在": "消える",
	"下线于": "オフラインになる",
	"从知觉中脱落于": "知覚から脱落する",
	"躲进": "隠れる",
	"塔下频道": "塔のふもとチャンネル",
	"固定场景": "固定場面",
	"我们楼下": "私たちの階下",
	"一颗月亮": "一つの月",
	"第二个月亮": "二つ目の月",
	"重复圆形": "反復する円形",
	"小月亮": "小さな月",
	"多出": "余分に現れる",
	"自动生成": "自動生成する",
	"发生复视": "二重に見える",
	"偷偷长出": "ひそかに生える",
	"昨夜影像": "昨夜の画像",
	"患者图像记录": "患者の画像記録",
	"你藏起来的照片": "あなたが隠した写真",
	"末班路线": "最終便の経路",
	"反复交通意象": "反復する交通イメージ",
	"接我们回家的车": "私たちを家へ運ぶバス",
	"没有抵达": "到着しない",
	"未刷新到": "更新されない",
	"无法到达": "到達できない",
	"忘了停在": "止まるのを忘れる",
	"终点": "終点",
	"最终页面": "最後のページ",
	"结束条件": "終了条件",
	"家的门口": "家の玄関",
	"废站广播": "廃駅の放送",
	"离线广播": "オフライン放送",
	"听觉内容": "聴覚内容",
	"墙里的喇叭": "壁の中のスピーカー",
	"喊出": "呼び上げる",
	"公开了": "公開する",
	"重复呼唤": "繰り返し呼ぶ",
	"学会了": "覚える",
	"我的名字": "私の名前",
	"用户实名": "ユーザーの実名",
	"自我称呼": "自己呼称",
	"我给你的名字": "私があなたに付けた名前",
	"封闭站台": "閉鎖されたホーム",
	"停用站点": "廃止された駅",
	"封闭场景": "閉鎖された場面",
	"没人等车的地方": "誰も待たない場所",
	"重新亮起": "再び点灯する",
	"恢复在线": "オンラインへ戻る",
	"再次显现": "再び現れる",
	"又睁开": "また目を開く",
	"十年前的灯": "十年前の明かり",
	"过期指示灯": "期限切れの表示灯",
	"陈旧光源记忆": "古い光源の記憶",
	"你忘掉的小灯": "あなたが忘れた小さな明かり",
	"便利店员": "コンビニ店員",
	"夜班账号": "夜勤アカウント",
	"无面孔人物": "顔のない人物",
	"替我们看门的人": "私たちの戸口を見張る人",
	"没有留下": "残さない",
	"删除了": "削除する",
	"未形成": "形成されない",
	"不肯带走": "持ち去ろうとしない",
	"影子": "影",
	"在线痕迹": "オンラインの痕跡",
	"自体投影": "自己投影",
	"脚下的黑朋友": "足元の黒い友だち",
	"预约推送": "予約投稿",
	"预期记录": "予期された記録",
	"明天塞进门缝的纸": "明日ドアの隙間に差し込まれる紙",
	"写着": "書かれている",
	"标记为": "として印を付ける",
	"诊断为": "と診断する",
	"偷偷叫作": "ひそかに呼ぶ",
	"我的失踪": "私の失踪",
	"用户离线": "ユーザーはオフライン",
	"对象缺席": "対象の不在",
	"你不回家": "あなたが帰らないこと",
	"历史缓存": "履歴キャッシュ",
	"既往记录": "既往記録",
	"以前写给你的信": "以前あなたに書いた手紙",
	"回复了": "返信する",
	"重新推送": "再投稿する",
	"回返为": "として戻る",
	"开口叫了": "声に出して呼ぶ",
	"当前账号": "現在のアカウント",
	"现时自我": "現在の自己",
	"现在陪我的你": "今ここにいるあなた",
	"地图": "地図",
	"导航服务": "ナビゲーションサービス",
	"空间图式": "空間図式",
	"你画的路线": "あなたが描いた道順",
	"删掉": "削除する",
	"隐藏": "隠す",
	"压抑": "抑圧する",
	"擦掉": "消し去る",
	"返程路线": "帰路",
	"退行路径": "退行経路",
	"回到我这里的路": "私のところへ戻る道",
	"门禁系统": "入退室システム",
	"行为记录": "行動記録",
	"门口那只眼睛": "戸口の目",
	"判定异常": "異常と判定する",
	"否定": "否定する",
	"假装没看见": "見なかったふりをする",
	"我在屋里": "私は部屋の中にいる",
	"用户已在家": "ユーザーはすでに帰宅",
	"对象仍在场": "対象はまだその場にいる",
	"你一直陪着我": "あなたはずっとそばにいる",
	"把发布过的词重新说给医生": "投稿した言葉を医師にもう一度話す",
	"同一个词到了这里会换一种说法。拖拽词块，或先点词块再点句槽。": "同じ言葉でも、ここでは別の言い方になる。ドラッグするか、言葉を選んでから文の枠を選ぶ。",
	"对医生说出口": "医師に話す",
	"缝线布偶 / GUIDE": "縫い目のあるぬいぐるみ / GUIDE",
	"你已经会自己走了。至少现在是。": "もう一人で歩ける。少なくとも今は。",
	"测试提示：继续探索。": "テスト：探索を続ける。",
	"已答对": "正解済み",
	"未完成": "未完了",
	"已拾取": "取得済み",
	"已显形": "出現済み",
	"未显形": "未出現",
	"本层测试：关键 NPC %s / 前置物 %s": "レベルテスト：重要NPC %s / 前提アイテム %s",
	"目标：%s。%s": "目標：%s。%s",
	"前置物": "前提アイテム",
	"跟随荧光测试标记。": "蛍光色のテスト表示を追う。",
	"隐藏层测试：前置物 %d/3 · 污染 %d/80 · 第三层结束检查": "隠しレベルテスト：前提アイテム %d/3 · 汚染 %d/80 · レベル3終了時に判定",
	"污染 %d%%  /  发布与现实表达会推进污染": "汚染 %d%%  /  投稿と現実での発話が汚染を進める",
	"拾取字词不增加污染；使用它才会改变语言。": "言葉を拾うだけでは汚染されない。使ったときに言語が変わる。",
	"今天没有可拾取的词": "今日は拾える言葉がない",
	"完整句子": "完全な文",
	"从帖子拾取原词，再按语法位置组成手机世界会使用的句子。": "投稿から元の言葉を拾い、文法上の位置へ並べて携帯の世界が使う文を作る。",
	"确认组成句子": "文を確定",
	"拾取词库": "拾った言葉",
	"词": "言葉",
	"对象": "主語",
	"动作": "動作",
	"去向": "目的語",
	"句子结构": "文の構造",
	"手机语言预览：%s": "携帯言語プレビュー：%s",
	"%s：%s": "%s：%s",
	"你说：%s": "あなたの発話：%s",
	"理解度：%d%%": "理解度：%d%%",
	"还没有能带到医生面前的词。先在手机里发布一句完整的话。": "まだ医師へ持っていける言葉がない。先に携帯で完全な文を投稿する。",
	"原词：%s": "元の言葉：%s",
	"手机里：%s": "携帯では：%s",
	"等待词语": "言葉を待っている",
	"原句：%s": "元の文：%s",
	"医生语言：%s": "医師の言語：%s",
	"句子尚未完整。需要对象、动作和去向。": "文はまだ完成していない。主語・動作・目的語が必要。",
	"第一层": "レベル1",
	"选中了一个带到医生面前的词。": "医師へ持っていく言葉を選んだ。",
	"词已经进入医生句槽。": "言葉が医師の文枠に入った。",
	"这个词不能放在句子的这个位置。": "この言葉は文のこの位置には置けない。",
	"先选择一个词。": "先に言葉を選ぶ。",
	"同一句话到了医生那里，已经不是原来的样子。": "同じ文でも、医師へ届いた時には元の形ではない。",
	"句子还不完整，或者这些词还没有在手机里发布。": "文が不完全か、言葉がまだ携帯で投稿されていない。",
	"完整句子已经写好：%s": "完全な文ができた：%s",
	"需要分别填入对象、动作和去向。": "主語・動作・目的語をそれぞれ入れる。",
	"等待对象、动作和去向": "主語・動作・目的語を待っている",
	"谁 / 什么": "誰 / 何",
	"放入主语": "主語を入れる",
	"发生了什么": "何が起きたか",
	"放入动作": "動作を入れる",
	"对谁 / 在哪里": "誰に / どこで",
	"放入落点": "目的語を入れる",
	"把你刚才放进手机的句子再说一遍。不要替它解释。": "さっき携帯に入れた文をもう一度話して。説明はしなくていい。",
	"医生记下的句子和你记得的并不相同。": "医師が書いた文は、あなたの記憶と同じではない。",
	"你从屏幕里带回了哪些词？按你认为原本的顺序说。": "画面からどの言葉を持ち帰った？ 元の順番だと思う通りに話して。",
	"医生在每个词旁边写下另一种用途。": "医師はそれぞれの言葉の横に別の用途を書く。",
	"请只使用仍属于你的词，描述你现在在哪里。": "まだあなたのものと言える言葉だけで、今いる場所を説明して。",
	"医生停笔。病历上的主语比你先消失。": "医師が筆を止める。カルテの主語があなたより先に消える。",
	"这些词没有来源。你还坚持它们是你选的吗？": "この言葉には出典がない。それでも自分で選んだと言える？",
	"没有人替这句话登记说话者。": "この文には話者が登録されていない。",
	"我会先念完屏幕教我的那句，然后说明路口为什么没有放我过去。": "まず画面に教わった文を言い終えてから、交差点が通してくれなかった理由を話す。",
	"我们不再问你叫什么。我们只核对手机替你说过哪一句话。": "もう名前は聞かない。携帯があなたの代わりに話した文だけを照合する。",
	"无名信徒在听见屏幕用词时微笑，在听见其余内容时闭上眼睛。": "名もなき信徒は画面の言葉で笑い、それ以外を聞くと目を閉じる。",
	"那句话跟着我，但我的名字仍然应该先于它出现。": "あの文はついてくる。それでも私の名前が先に現れるべきだ。",
	"出示旧句": "古い文を見せる",
	"我们顺着屏幕留下的标记走，看看旧句子把终点改到了哪里。": "画面の印をたどり、古い文が終点をどこへ移したか確かめる。",
	"旧句之后": "古い文のあと",
	"等它念完屏幕借来的话，我要在第一个属于今天的停顿下车。": "画面から借りた言葉を読み終えたら、今日に属する最初の間で降りる。",
	"墙里的回声开始替我们回答，而且每次都比原话多一句屏幕里的旧话。要把哪一句留下？": "壁のこだまが代わりに答え、毎回画面の古い文を一つ足す。どの文を残す？",
	"只留下我们刚才说的句子，旧话可以经过，但不要冒充回声。": "今話した文だけを残す。古い言葉は通ってもいいが、こだまのふりはさせない。",
	"标记旧话": "古い言葉に印を付ける",
	"把多出来的旧话标上来源，让它不能假装今天才出生。": "余分な古い言葉に出典を付け、今日生まれたふりをさせない。",
	"档案柜要求给你的每句话填写“词语来源”。原创一栏已经被涂黑。你填什么？": "書庫はすべての文に「言葉の出典」を求める。オリジナル欄は黒く塗られている。何を書く？",
	"来自旧帖": "古い投稿から",
	"旧帖里的句子会自己寻找嗓子，圣歌只是它们同时借到人的时刻。": "古い投稿の文は自分で喉を探す。聖歌とは、同時に人を借りた瞬間にすぎない。",
	"打开最早的一条，看看是谁先把未来误认成了旧记录。": "最も古い一件を開き、誰が最初に未来を過去の記録と見誤ったか確かめる。",
	"从三个词开始。先让它们组成一句完整的话，再看这句话到了另一个世界会变成什么。": "三つの言葉から始める。完全な文を作り、別の世界で何に変わるか見る。",
	"所有被发布过的句子都说智者住在这里。这里没有智者。": "投稿された文はすべて賢者がここに住むと言う。ここに賢者はいない。",
	"最后一条回复只剩三个被划掉的词。帖子问：这句话原本是谁说的？": "最後の返信には、消された三つの言葉だけが残っている。投稿は問う。この文を元々言ったのは誰だった？",
	"旧帖目击者没有截屏。三个词自行保存，却把说话者留成空白。": "旧投稿の目撃者はスクリーンショットを撮らなかった。三つの言葉はひとりでに保存され、話者だけを空白に残した。",
	"第四层没有登记记录。": "レベル4には登録記録がない。",
	"你抵达了第 %d 层。": "レベル%dに到達した。",
	"用你从屏幕里带回来的词说一句完整的话。": "画面から持ち帰った言葉で完全な文を一つ話す。",
	"医生把句子写了下来。": "医師は文を書き留めた。",
	"句子「%s」": "文「%s」",
	"TEST  教程引导": "TEST  チュートリアル案内",
	"TEST  隐藏路线关键 NPC": "TEST  隠しルート重要NPC",
	"TEST  医生 / 语言拼句": "TEST  医師 / 文パズル",
	"TEST  前置物：%s": "TEST  前提アイテム：%s",
	"医生": "医師",
	"布偶把缝线朝向了下一步。": "ぬいぐるみは縫い目を次の手順へ向けた。",
	"布偶重复了一遍刚才的方向。": "ぬいぐるみはもう一度同じ方向を指した。",
	"那一段话还没有长到你能听见的位置。": "その言葉は、まだ聞こえる場所まで育っていない。",
	"它让你先照做，理由可以晚一点再问。": "まず言われた通りにする。理由はあとで聞けばいい。",
	"缝线布偶指向了下一步。": "縫い目のあるぬいぐるみが次の手順を指した。",
	"你把我放反了。缝口应该朝着路，不是朝着你。先拿起手机。帖子里有三种能拼成一句话的词。": "私を逆向きに置いた。縫い口はあなたではなく道へ向ける。まず携帯を持って。投稿には文を作る三種類の言葉がある。",
	"布偶把一只纽扣眼转向手机。它没有催你，但路边的测试标记亮了。": "ぬいぐるみはボタンの片目を携帯へ向けた。急かさないが、道端のテスト表示が光った。",
	"先打开手机": "まず携帯を開く",
	"我先去看帖子。三个词，拼成一句完整的话。": "先に投稿を見る。三つの言葉で完全な文を作る。",
	"先打开社交媒体，再打开任意一篇帖子。": "まずSNSを開き、好きな投稿を一つ開く。",
	"为什么是三个": "なぜ三つなのか",
	"为什么一定要三个词？少一个会发生什么？": "なぜ三つの言葉が必要？ 一つ足りないとどうなる？",
	"对象、动作、去向。少一个，手机就会替你补。": "主語、動作、目的語。一つ欠けると携帯が代わりに補う。",
	"问词属于谁": "言葉の持ち主を聞く",
	"帖子里的词属于写下它的人，还是拾走它的人？": "投稿の言葉は書いた人のもの、それとも拾った人のもの？",
	"先拾取。等你使用它时，再看它选择了谁。": "まず拾う。使ったとき、言葉が誰を選ぶか見る。",
	"它又指向手机。三个词。对象、动作、去向。": "また携帯を指す。三つの言葉。主語、動作、目的語。",
	"你把那句话发出去了。现在放下手机，去找医生。不要换词，只换说话的地方。": "あの文を投稿した。今度は携帯を置いて医師を探す。言葉は変えず、話す場所だけを変える。",
	"布偶摸了摸右眼的纽扣。相同的三个词在里面排成了另一句话。": "ぬいぐるみは右目のボタンに触れた。同じ三つの言葉が中で別の文になる。",
	"去找医生": "医師を探す",
	"我会用发布过的词，再说一次同样的句子。": "投稿した言葉で、同じ文をもう一度話す。",
	"医生就在这一层，荧光测试标记会指出位置。": "医師はこのレベルにいる。蛍光色のテスト表示が場所を示す。",
	"问词为什么会变": "言葉が変わる理由を聞く",
	"如果词没有换，为什么句子的意思会变？": "言葉が同じなら、なぜ文の意味が変わる？",
	"因为手机和医生都坚持自己才是词的原主人。": "携帯も医師も、自分こそ言葉の元の持ち主だと言い張るから。",
	"不替句子解释": "文の代わりに説明しない",
	"我只把词放进去，不替任何一个世界解释。": "言葉を置くだけにする。どちらの世界の代わりにも説明しない。",
	"很好。让两个版本并排留下。": "いい。二つの版を並べて残す。",
	"它重复：发布过的词才能带到医生面前。": "繰り返す。投稿した言葉だけが医師の前へ持っていける。",
	"这一层会检查你从下面带回来的东西。记录没有写数量，也没有写检查会在什么时候发生。": "このレベルは下から持ち帰ったものを調べる。記録には数も、いつ調べるかも書かれていない。",
	"布偶腹部的缝线自己松开一针。里面不是棉花，是一小段没有登记的楼梯声。": "ぬいぐるみの腹の縫い目が一針ほどける。中に綿はなく、未登録の階段の音が少し入っている。",
	"检查带回的东西": "持ち帰ったものを確認する",
	"我会确认从下面带回来的东西都还在。": "下から持ち帰ったものが全部残っているか確かめる。",
	"不要只数口袋。也要记住是谁告诉你去找它们。": "ポケットだけを数えない。それを探せと言った相手も覚えておく。",
	"问检查的时机": "検査の時機を聞く",
	"要到什么时候，这一层才会承认我已经准备好？": "いつになれば、このレベルは準備ができたと認める？",
	"等语言再也装不成干净的时候，出口才会做一次检查。": "言語がもう清潔なふりをできなくなったとき、出口が一度だけ検査する。",
	"问不存在的楼层": "存在しないレベルを聞く",
	"如果还有下一层，为什么所有记录都只写到这里？": "次のレベルがあるなら、なぜ記録はすべてここで終わる？",
	"因为那一层不是被锁住，而是没有被承认。": "そのレベルは施錠されたのではなく、認められていないから。",
	"它的腹部已经缝好。针脚数量和记录里的空格对不上。": "腹は再び縫い合わされた。針目の数が記録の空欄と合わない。",
	"用双手拇指与食指的四个指尖框出矩形区域，区域内会显示手机层。视频只在本机用于关键点计算，不写入存档。": "両手の親指と人差し指、四本の指先で長方形を作る。その内側に携帯の層が表示される。映像は端末内のランドマーク計算にのみ使い、保存しない。",
	"等待双手四指框选": "両手の四本指で作る枠を待機中",
	"已从系统摄像头编号 %d 收到画面。放下游戏内手机，用双手拇指与食指的四个指尖框出矩形。": "システムカメラ番号%dから映像を受信。ゲーム内の携帯を置き、両手の親指と人差し指で長方形を作る。",
}


static func entries(locale_code: String) -> Dictionary:
	match locale_code.to_lower():
		"en":
			return EN
		"ja":
			return JA
		_:
			return {}
