extends RefCounted


const EN: Dictionary = {
	# Tags, signal patterns, tarot, and reusable sentence blocks.
	"哈吉米": "Hajimi",
	"追问": "Follow-up Question",
	"日常": "Everyday",
	"空位": "Empty Seat",
	"沉默": "Silence",
	"巴别塔": "Tower of Babel",
	"信徒": "Believer",
	"刷新": "Refresh",
	"反问": "Counterquestion",
	"禁问": "Forbidden Question",
	"圣歌": "Hymn",
	"双声回路": "Dual-Voice Circuit",
	"命中至少 2 个今日风向": "Match at least 2 of today's trends",
	"杂讯列阵": "Noise Array",
	"成品含至少 4 种隐藏标签": "Use at least 4 distinct hidden tags",
	"独字成句": "One-Word Sentence",
	"发布一个只含 1 个字的基础梗": "Publish a basic meme containing exactly one word",
	"空位对子": "Empty-Seat Pair",
	"同时含有「空位」和「沉默」": "Include Empty Seat and Silence",
	"巴别直线": "Babel Straight",
	"集齐「巴别塔」「信徒」「圣歌」": "Collect Tower of Babel, Believer, and Hymn",
	"禁问回环": "Forbidden-Question Loop",
	"复读一次并带有反问或禁问": "Repeat once with Counterquestion or Forbidden Question",
	"星星": "The Star",
	"命中至少 2 个风向时，整数倍率额外 +1。": "Match at least 2 trends: multiplier +1.",
	"太阳": "The Sun",
	"每次发布获得额外 14 点传播基础。": "Each post gains +14 base reach.",
	"月亮": "The Moon",
	"污染达到 40% 时，传播基础 +16。": "At 40% corruption or higher, base reach +16.",
	"隐者": "The Hermit",
	"第一次复用相同表达不触发衰减。": "The first reuse of the same expression ignores repeat decay.",
	"高塔": "The Tower",
	"融合梗的整数倍率额外 +1。": "Fused meme multiplier +1.",
	"倒吊人": "The Hanged Man",
	"每条遗产造成的隐性交流损耗减少 4。": "Reduce each Legacy Rule's communication penalty by 4.",
	"审判": "Judgement",
	"今日牌型成立时再获得 18 点传播基础。": "Complete today's pattern: base reach +18.",
	"不分昼夜": "Day and Night",
	"每天多 1 次行动。": "+1 action per day.",
	"星坠高塔": "Starfall Tower",
	"融合梗的整数倍率再 +1。": "Fused meme multiplier +1 again.",
	"月下隐者": "Hermit by Moonlight",
	"额外忽略 1 次复读衰减。": "Ignore one additional repeat penalty.",
	"我": "I",
	"想": "want to",
	"正常": "clearly",
	"说明": "explain",
	"这件事": "this",
	"不是": "that wasn't",
	"那个意思": "what I meant",
	"请": "please",
	"听我": "hear me out",
	"说完": "let me finish",
	"哈吉米，必须补票": "Hajimi, you must pay the missing fare",
	"在线本身就是发言": "Being online is itself a statement",
	"请用更新后的句式进入": "Please enter using the updated sentence form",
	"你为什么需要他说话": "Why do you need them to speak?",

	# Generic reality responses.
	"直接说明": "Explain directly",
	"我只是想把刚才的事情说清楚。": "I only want to explain what just happened.",
	"先道歉": "Apologize first",
	"对不起，我没有想让你觉得被忽视。": "I'm sorry. I didn't mean to make you feel ignored.",
	"请你再说": "Ask them to repeat",
	"请你再说一遍，我想认真听完。": "Please say it again. I want to hear you out.",
	"询问商品": "Ask about the goods",
	"我想看看能帮助沟通的东西。": "I'd like to see something that can help us communicate.",
	"说明来意": "Explain your need",
	"我需要让别人更容易听懂我。": "I need something that will make me easier to understand.",
	"试探价格": "Ask the price",
	"这些东西分别需要多少钱？": "How much does each one cost?",

	# Reality floor 1.
	"你也在等那班已经经过、但谁都没看见的车吗？": "Are you also waiting for the bus that already passed, even though no one saw it?",
	"迟到者看了一眼空荡荡的站牌，像是在替它保守秘密。": "The Latecomer glanced at the deserted bus stop as if keeping its secret.",
	"一起等": "Wait together",
	"我没有看见那班车，但我可以陪你再等一会儿。": "I didn't see the bus, but I can wait here with you a little longer.",
	"核对时间": "Check the time",
	"站牌上的时间没有变，也许车还没有真正经过。": "The time on the sign hasn't changed. Maybe the bus hasn't truly passed yet.",
	"先离开": "Leave for now",
	"如果下一班也没有声音，我们就沿着路走回去。": "If the next bus makes no sound either, we'll follow the road back on foot.",
	"楼上的水管昨晚喊了我的名字。你住哪一户？": "The pipes upstairs called my name last night. Which unit do you live in?",
	"回声住户把钥匙攥紧了一点，管道在墙里轻轻敲了三下。": "The Echo Resident tightened their grip on the key. The pipes tapped softly three times inside the wall.",
	"说出住处": "Say where you live",
	"我住在路尽头那扇总是关不严的门后面。": "I live behind the door at the end of the road, the one that never quite closes.",
	"问水管": "Ask about the pipes",
	"也许水管只是记住了你每天回家的脚步声。": "Maybe the pipes only memorized the sound of your footsteps coming home each day.",
	"确认名字": "Check the name",
	"它喊的是你的名字，还是住在这里的每一个名字？": "Did they call your name, or every name that lives here?",
	"我把门牌抄了三遍，每一遍都少一个人。你能替我数吗？": "I copied the doorplates three times. Each copy was missing one person. Can you count them for me?",
	"抄写员没有递出纸，只把空着的第四行折进掌心。": "The Copyist did not hand over the paper. They folded the empty fourth line into their palm.",
	"重新数": "Count again",
	"我们从第一扇门开始，名字和门牌分开数。": "Let's start at the first door and count the names and doorplates separately.",
	"保留空行": "Keep the blank line",
	"少掉的人也许需要一个空位置，而不是另一个名字。": "The missing person may need an empty place, not another name.",
	"停止抄写": "Stop copying",
	"先别写第四遍，纸可能正在学习怎样删掉人。": "Don't make a fourth copy yet. The paper may be learning how to erase people.",
	"你刚才抬头了吗？塔上掉下来一片像收据的云。": "Did you look up just now? A cloud shaped like a receipt fell from the tower.",
	"无名信徒把那片不存在的纸塞进口袋，动作十分熟练。": "The Nameless Believer slipped the nonexistent paper into a pocket with practiced ease.",
	"描述天空": "Describe the sky",
	"我只看见绿色的天，云上没有价格，也没有日期。": "All I saw was a green sky. The cloud had no price and no date.",
	"索要收据": "Ask for the receipt",
	"如果它真是收据，上面应该写着是谁买下了这座塔。": "If it's really a receipt, it should say who bought this tower.",
	"看着地面": "Watch the ground",
	"我没有抬头，我怕地面趁机换掉回去的方向。": "I didn't look up. I was afraid the ground would replace the way back while I wasn't watching.",
	"我在十年前的帖子里看见今天的你。那是你吗？": "I saw you as you are today in a post from ten years ago. Was that you?",
	"旧帖目击者没有展示截图，屏幕却自行亮了一瞬。": "The Old-Post Witness showed no screenshot, but the screen lit by itself for an instant.",
	"承认": "Admit it",
	"如果照片里的我正在等今天，那个人也可以算是我。": "If the person in the photo is waiting for today, they can count as me.",
	"否认": "Deny it",
	"十年前我不在这里，帖子也不该记得我的脸。": "I wasn't here ten years ago, and the post shouldn't remember my face.",
	"留下回复": "Leave a reply",
	"请替我回复一句，让过去不要继续往前翻页。": "Please reply for me. Tell the past not to keep scrolling ahead.",

	# Reality floor 2.
	"先说上一层留下的那句话，再告诉我你为什么迟到。顺序不能反。": "First recite the sentence left by the floor below, then tell me why you're late. You may not reverse the order.",
	"迟到者认真听完规定的部分，剩下的话被风带到很远。": "The Latecomer listened carefully to the required part; the wind carried the rest far away.",
	"照顺序说": "Follow the order",
	"我会先念完遗产，然后说明路口为什么没有放我过去。": "I'll recite the legacy first, then explain why the intersection wouldn't let me pass.",
	"先说理由": "Give the reason first",
	"我迟到是因为那条路反复把我送回同一块路牌。": "I'm late because that road kept sending me back to the same sign.",
	"拒绝顺序": "Reject the order",
	"如果原因只能排在旧话后面，它就不再是我的原因。": "If my reason can only come after an old sentence, it is no longer my reason.",
	"这层每户都要保管一句旧话。我家的那句半夜会自己换位置。": "Every home on this floor has to keep an old sentence. Mine changes places by itself at midnight.",
	"回声住户点了点头，像是刚完成一次例行点名。": "The Echo Resident nodded as if completing a routine roll call.",
	"锁住它": "Lock it down",
	"把那句话写在门背后，也许它就找不到新的房间。": "Write it behind the door. Maybe then it won't find a new room.",
	"记录移动": "Track its movement",
	"今晚记下它每次换位置的时间，不要改动其中的字。": "Tonight, record every time it moves. Don't change any of its words.",
	"送回楼下": "Send it downstairs",
	"旧话来自上一层，我们可以沿楼梯把它送回原处。": "The old sentence came from below. We can carry it back down the stairs.",
	"登记表说你已经回答过了。可我这里还是空白。": "The registry says you've already answered. But my copy is still blank.",
	"抄写员在空白处盖章，印泥发出一声很轻的叹息。": "The Copyist stamped the blank. The ink pad let out a faint sigh.",
	"再回答": "Answer again",
	"我可以再说一次，但请保留这次说话留下的空白。": "I can say it again, but please preserve the blank this telling leaves behind.",
	"质疑记录": "Challenge the record",
	"表格记住的是动作，不一定记住了我真正说过什么。": "The form remembers the act, not necessarily what I actually said.",
	"请求盖章": "Request a stamp",
	"请先证明这里曾经空着，再把我的句子写进去。": "First prove that this space was once blank. Then write my sentence into it.",
	"我们不再问你叫什么。我们只核对你携带了哪一句遗产。": "We no longer ask your name. We only verify which legacy sentence you carry.",
	"无名信徒在听见遗产时微笑，在听见其余内容时闭上眼睛。": "The Nameless Believer smiled when they heard the legacy and closed their eyes to everything else.",
	"坚持名字": "Insist on your name",
	"遗产跟着我，但我的名字仍然应该先于它出现。": "The legacy follows me, but my name should still appear before it.",
	"出示遗产": "Present the legacy",
	"我带着上一层最响的句子，它比我更容易被认出来。": "I carry the loudest sentence from the floor below. It is easier to recognize than I am.",
	"声称空手": "Claim to be carrying nothing",
	"我想试着什么都不携带，只用今天剩下的词站在这里。": "I want to stand here carrying nothing, using only the words left from today.",

	# Reality floor 3.
	"请提交一句未被使用过的自己。重复部分将退回上一窗口。": "Please submit a version of yourself that has never been used. Any repeated portion will be returned to the previous counter.",
	"迟到者撕下回执，纸的背面印着同一张回执。": "The Latecomer tore off the receipt. The same receipt was printed on its back.",
	"提交原句": "Submit an original sentence",
	"这句话只在现在出现，请不要替它补上以前的编号。": "This sentence exists only now. Please don't assign it an earlier number.",
	"承认重复": "Admit repetition",
	"我借用了旧句子的结构，但其中的犹豫是今天才有的。": "I borrowed an old sentence's structure, but its hesitation belongs to today.",
	"寻找窗口": "Find the counter",
	"上一窗口已经封死，我只能把退件留在这里。": "The previous counter is sealed. I can only leave the rejected form here.",
	"你所在的住处已被归类为比喻。实体住址需要另行申请。": "Your residence has been classified as a metaphor. A physical address requires a separate application.",
	"回声住户把申请表对折，折痕恰好穿过自己的地址。": "The Echo Resident folded the application in half. The crease ran precisely through their address.",
	"申报实体": "Declare it physical",
	"我的房间有墙和门，也有一盏会在凌晨熄灭的灯。": "My room has walls and a door, and a lamp that goes out before dawn.",
	"接受比喻": "Accept the metaphor",
	"如果住处只是比喻，请注明我究竟被比作了什么。": "If my home is only a metaphor, please specify what I am being compared to.",
	"撤销地址": "Cancel the address",
	"取消我的地址吧，这样回去的时候就不会再次走错。": "Cancel my address. Then I won't get lost again when I try to go home.",
	"缺失人员栏不能留空。请填写一个仍然存在的人。": "The missing-person field cannot be left blank. Enter someone who still exists.",
	"抄写员将答案归档，抽屉里传来某个人翻身的声音。": "The Copyist filed the answer. Someone shifted inside the drawer.",
	"填写自己": "Enter your own name",
	"先写我的名字，至少此刻我还站在表格外面。": "Put down my name first. At least for now, I'm still standing outside the form.",
	"保留缺失": "Preserve the absence",
	"缺失不是空白，它是一个人离开后留下的准确形状。": "Missing is not blank. It is the exact shape left after a person leaves.",
	"询问抽屉": "Ask about the drawer",
	"请打开抽屉，里面的人也许知道自己是否仍然存在。": "Open the drawer. The person inside may know whether they still exist.",

	# Reality floors 4 and 5.
	"我们唱到你的名字时，请不要回答。回答会破坏和声。": "When we sing your name, do not answer. Answering will ruin the harmony.",
	"合唱没有停下，只在主角应该出现的位置稍微变调。": "The choir did not stop; it merely went slightly out of tune where the protagonist should have entered.",
	"保持沉默": "Stay silent",
	"我会让名字从我身边经过，不把它认领回来。": "I'll let the name pass by me without claiming it back.",
	"打断合唱": "Interrupt the choir",
	"那是我的名字，它不该只作为你们旋律里的一个音。": "That is my name. It shouldn't exist only as a note in your melody.",
	"轻声跟唱": "Hum along",
	"我只跟着最后一个音，不唱名字，也不唱塔。": "I'll follow only the final note. I won't sing the name or the tower.",
	"圣歌需要一个空位。大家一致认为那个位置很像你。": "The hymn needs an empty place. Everyone agrees that place looks like you.",
	"无名信徒向旁边挪开半步，空位却仍然跟着主角。": "The Nameless Believer shifted half a step aside, but the empty place kept following the protagonist.",
	"站进空位": "Step into the empty place",
	"我可以站在那里，但不会把沉默假装成赞同。": "I can stand there, but I won't pretend silence means consent.",
	"拒绝位置": "Refuse it",
	"像我不等于属于我，请把那个位置继续空着。": "Looking like me does not make it mine. Leave it empty.",
	"询问缺席者": "Ask about the absent person",
	"这个空位原来属于谁，你们为什么不再唱那个人？": "Who did this empty place belong to, and why don't you sing them anymore?",
	"你 / 还 / 把 / 自己 / 带着吗": "ARE / YOU / STILL / CARRYING / YOURSELF",
	"迟到者的嘴唇动了五次，只有斜线抵达空气。": "The Latecomer's lips moved five times. Only the slashes reached the air.",
	"仍在这里": "Still here",
	"我还在这里，只是句子比我先到了一步。": "I'm still here. The sentence simply arrived one step ahead of me.",
	"遗失一部分": "Lost a part",
	"有一部分留在楼下，正在替我继续回答问题。": "Part of me stayed downstairs and is still answering questions for me.",
	"逐字确认": "Count word by word",
	"我会一个字一个字地数，数到停下的地方就是我。": "I'll count myself one word at a time. Wherever the count stops is where I am.",
	"窗 / 外 / 有 / 一只 / 没有过去的鸟": "OUTSIDE / THE WINDOW / IS / A BIRD / THAT NEVER FLEW PAST",
	"旧帖目击者望向窗外。那里没有窗，鸟仍然飞过了一次。": "The Old-Post Witness looked outside. There was no window, yet the bird still passed by once.",
	"描述那只鸟": "Describe the bird",
	"它没有向前飞，只让身后的世界不断离开。": "It never flies forward. It only makes the world behind it keep leaving.",
	"寻找窗户": "Find the window",
	"先找到窗户吧，不然我们不知道外面究竟属于哪里。": "Let's find the window first. Otherwise we won't know where outside belongs.",
	"发送信号": "Send a signal",
	"如果它没有过去，就让这句话追上它，替我们问候一次。": "If it never passed, let this sentence catch up and greet it for us.",

	# Extended reality conversations.
	"站牌忽然显示“无信号”。可这条街从来没有接入过线路。你还要等吗？": "The stop display suddenly reads \"NO SIGNAL.\" But this street was never connected to a network. Will you keep waiting?",
	"迟到者把手机举向塔影，屏幕上的叉号短暂变成一扇门。": "The Latecomer raised their phone toward the tower's shadow. For a moment, the cross on the screen became a door.",
	"继续等候": "Keep waiting",
	"再等一班吧；没有线路，不等于没有人正试着抵达。": "Let's wait for one more. No network does not mean no one is trying to arrive.",
	"追查塔影": "Trace the tower's shadow",
	"信号也许不是从天上消失，而是被塔一层层收走了。": "Perhaps the signal did not vanish from the sky. Perhaps the tower collected it floor by floor.",
	"沿路步行": "Walk the route",
	"我们顺着遗产标记走，看看旧句子把终点改到了哪里。": "Let's follow the legacy markers and see where the old sentences moved the terminus.",
	"车终于来了。报站器只念上一层留下的梗，不再念地名。你在哪里下车？": "At last the bus arrives. Its announcer recites only the meme left by the floor below, never a place name. Where will you get off?",
	"迟到者在没有地名的一站按铃。车门打开，塔的影子没有跟下来。": "The Latecomer rang the bell at a stop with no name. The doors opened, and the tower's shadow did not follow them out.",
	"遗产之后": "After the legacy",
	"等它念完遗产，我要在第一个属于今天的停顿下车。": "When it finishes the legacy, I'll get off at the first pause that belongs to today.",
	"沉默站点": "The silent stop",
	"没有报站声的地方就是我的站，至少那里还没有被命名。": "The place with no announcement is my stop. At least it has not been named yet.",
	"留在车上": "Stay aboard",
	"我先不下车，直到有人用自己的话说出一个方向。": "I will stay aboard until someone gives a direction in words of their own.",
	"报站声被污染成连续的旧梗。迟到者捂住听筒，车还没有来，谈话先驶远了。": "The announcement decayed into a stream of old memes. The Latecomer covered the receiver; the bus had not arrived, but the conversation had already gone.",
	"墙里的回声开始替我们回答，而且每次都比原话多一句遗产。要把哪一句留下？": "The echo in the wall has begun answering for us, adding one legacy sentence every time. Which sentence should remain?",
	"回声住户贴近墙面，听见自己的声音从更高一层缓慢返回。": "The Echo Resident leaned close to the wall and heard their own voice returning slowly from a higher floor.",
	"留下原话": "Keep the original",
	"只留下我们刚才说的句子，遗产可以经过，但不要冒充回声。": "Keep only the sentence we just spoke. The legacy may pass through, but it must not pose as an echo.",
	"标记遗产": "Mark the legacy",
	"把多出来的旧话标上楼层，让它不能假装今天才出生。": "Mark the extra old sentence with its floor, so it cannot pretend it was born today.",
	"关闭管道": "Close the pipe",
	"先关掉这段管道，沉默也比被替写的回答更诚实。": "Close this section of pipe. Even silence is more honest than an answer written over us.",
	"水龙头流出一串陌生口音。住户说这就是语言污染的味道。你怎么确认还是水？": "A chain of unfamiliar accents runs from the tap. The resident calls it the taste of language corruption. How do you confirm it is still water?",
	"回声住户接住一滴无声的水。它没有复述任何人，钥匙终于松开。": "The Echo Resident caught one silent drop. It repeated no one, and their grip on the key finally loosened.",
	"观察倒影": "Watch the reflection",
	"如果倒影还会被波纹打断，它至少没有完全变成一句口号。": "If ripples can still interrupt its reflection, at least it has not become a slogan completely.",
	"尝试命名": "Try naming it",
	"先叫它水一次；如果它立刻要求复读，我们就换一个杯子。": "Call it water once. If it immediately demands repetition, we will use another cup.",
	"保持无名": "Leave it unnamed",
	"不急着命名，让它在语言找到之前先作为液体留下。": "Do not rush to name it. Let it remain a liquid until language finds it.",
	"管道抢先说完所有答案。回声住户关上阀门，墙里仍有人继续这场谈话。": "The pipes spoke every answer before us. The Echo Resident shut the valve, but someone in the wall kept the conversation going.",
	"档案柜要求给你的每句话填写“遗产来源”。原创一栏已经被涂黑。你填什么？": "The archive cabinet requires a \"legacy source\" for every sentence you speak. The Original field has been blacked out. What will you enter?",
	"抄写员把表格转过来，背面密密麻麻都是尚未发生的引用。": "The Copyist turned the form over. Its back was crowded with citations that had not happened yet.",
	"填写此刻": "Enter this moment",
	"来源写此刻；这句话也许借过词，但犹豫是我自己的。": "Write this moment as the source. The sentence may borrow words, but the hesitation is mine.",
	"拒绝来源": "Refuse a source",
	"我不替活着的话伪造祖先，请把这一栏保持空白。": "I will not forge an ancestor for a living sentence. Leave this field blank.",
	"登记污染": "Register corruption",
	"标注语言污染；相似不一定是继承，也可能是感染。": "Mark it as language corruption. Resemblance is not always inheritance; it may be infection.",
	"盖章机说，未被塔收录的句子不算存在。抄写员把印章递给你。": "The stamping machine says a sentence not registered by the tower does not exist. The Copyist offers you the stamp.",
	"抄写员收回没有落下的印章，把你的句子夹进两页制度之间。": "The Copyist took back the unused stamp and slipped your sentence between two pages of procedure.",
	"不盖印章": "Do not stamp it",
	"存在不该由塔批准；让这句话带着空白离开档案。": "Existence should not require the tower's approval. Let this sentence leave the archive with its blank intact.",
	"盖在边缘": "Stamp the edge",
	"只盖在纸的边缘，证明制度碰过它，却没有拥有它。": "Stamp only the edge, proving the system touched it without owning it.",
	"改写条款": "Rewrite the clause",
	"先把条款改成“说出即存在”，再决定是否需要印章。": "First rewrite the clause as \"spoken means existing.\" Then decide whether a stamp is needed.",
	"盖章机吞掉了句子的主语。抄写员拉下断电杆，本次登记以空白中止。": "The stamping machine swallowed the sentence's subject. The Copyist cut the power, ending this registration in a blank.",
	"塔里的发射机没有接线，信徒却说每晚都能收到圣歌。你认为声音从哪里来？": "The transmitter in the tower has no wiring, yet the believer receives a hymn every night. Where do you think the sound comes from?",
	"无名信徒仰头辨认那段旋律，塔窗一层接一层地亮错顺序。": "The Nameless Believer looked up to identify the melody. The tower windows lit floor by floor in the wrong order.",
	"来自人群": "From the crowd",
	"也许是人群在塔下互相复述，最后忘了第一句话属于谁。": "Perhaps the crowd repeats itself below the tower until everyone forgets who owned the first sentence.",
	"来自遗产": "From the legacy",
	"遗产梗会自己寻找嗓子，圣歌只是它们同时借到人的时刻。": "Legacy memes seek out voices. A hymn is simply the moment they all borrow people at once.",
	"来自静电": "From static",
	"没有信号时，静电也会被当成启示；先别急着跪下。": "With no signal, even static can pass for revelation. Do not kneel just yet.",
	"信徒请你献出一句不会污染别人的话，作为进入上层的圣歌。": "The believer asks you to offer a sentence that will not corrupt anyone else, a hymn for entering the floor above.",
	"无名信徒没有唱你的句子，只把它安静地留在门外。塔门第一次自己开了。": "The Nameless Believer did not sing your sentence. They left it quietly outside, and the tower door opened by itself for the first time.",
	"保留疑问": "Keep a question",
	"我只能献出一个问题：我们是否允许别人不回答。": "I can offer only a question: do we allow other people not to answer?",
	"归还名字": "Return the names",
	"把每个人的名字还给本人，不把它们编进共同的副歌。": "Return every name to its owner. Do not weave them into a shared refrain.",
	"献出停顿": "Offer a pause",
	"我献出一句话结束后的停顿，让下一人有地方开口。": "I offer the pause after a sentence ends, so the next person has room to speak.",
	"圣歌突然只剩同一个梗。无名信徒停止合唱，塔门在污染扩散前合上。": "The hymn suddenly collapsed into one repeated meme. The Nameless Believer stopped singing, and the tower door shut before the corruption spread.",
	"旧帖显示这里“信号满格”，可所有回复都写着十年后发送。你要点开哪一条？": "The old post shows \"FULL SIGNAL,\" but every reply is marked as sent ten years from now. Which one will you open?",
	"旧帖目击者滑动屏幕，日期栏像坏掉的电梯一样上下跳动。": "The Old-Post Witness scrolled. The date field lurched up and down like a broken elevator.",
	"最早回复": "Earliest reply",
	"打开最早的一条，看看是谁先把未来误认成了遗产。": "Open the earliest one and see who first mistook the future for a legacy.",
	"未发回复": "Unsent reply",
	"打开那条尚未发送的，也许它还来得及换一种说法。": "Open the one not yet sent. It may still have time to say things differently.",
	"关闭帖子": "Close the post",
	"先关掉帖子；无信号时，时间不该假装自己已经上传。": "Close the post first. With no signal, time should not pretend it has already uploaded itself.",
	"最后一条回复只有一个梗框，里面空着。帖子问：要把今天的哪个词留给过去？": "The final reply contains only an empty Meme Frame. The post asks: which word from today will you leave to the past?",
	"旧帖目击者没有截屏。空框自行保存，又把今天完整地退还给你。": "The Old-Post Witness took no screenshot. The empty frame saved itself, then returned today to you intact.",
	"留下存在": "Leave existence",
	"留下“存在”；过去需要知道我们没有只活成引用。": "Leave \"existence.\" The past should know we did not live only as quotations.",
	"留下无信号": "Leave no signal",
	"留下“无信号”；让未来明白沉默也可能是线路断了。": "Leave \"no signal.\" Let the future know silence can also mean a broken connection.",
	"什么不留": "Leave nothing",
	"什么都不留；过去不该提前继承我们尚未说完的话。": "Leave nothing. The past should not inherit words we have not finished speaking.",
	"帖子开始自动复制你尚未说出的词。旧帖目击者拔掉电源，屏幕仍亮在中断处。": "The post began copying words you had not spoken yet. The Old-Post Witness pulled the plug, but the screen remained lit at the interruption.",

	# Signal Merchant dialogue and choices.
	"我卖的是能装住一个字的空框。字会漏出来，框不会。": "I sell empty frames that can hold one word. The word leaks out; the frame does not.",
	"信号商人敲了敲柜台，空框发出比内容更清楚的声音。": "The Signal Merchant tapped the counter. The empty frame rang clearer than anything it could contain.",
	"本层交易必须附上一句遗产。价格不会因此减少。": "Every transaction on this floor must include a legacy sentence. The price will not be reduced.",
	"信号商人收走了声音，没有说明它被记在哪一本账里。": "The Signal Merchant took the sound without saying which ledger recorded it.",
	"请确认购买者与说话者为同一实体。无法确认也可以签字。": "Please confirm that the buyer and the speaker are the same entity. If you cannot, you may still sign.",
	"信号商人把签名盖在照片上，照片里的人没有动。": "The Signal Merchant stamped the signature onto the photograph. The person in it did not move.",
	"交换也是圣歌。你给出一句，我归还一个更响的空位。": "Exchange is also a hymn. Give me a sentence, and I will return a louder empty place.",
	"信号商人低声唱出价格，数字在最后一个音里消失。": "The Signal Merchant sang the price under their breath; the number vanished into the final note.",
	"买 / 卖 / 留下 / 哪一个": "BUY / SELL / LEAVE BEHIND / WHICH ONE",
	"信号商人伸出空手。主角无法判断交易是否已经发生。": "The Signal Merchant held out an empty hand. The protagonist could not tell whether the transaction had already occurred.",
	"询问梗框": "Ask about Meme Frames",
	"我想要一个只装一个字的框，它不需要替我解释。": "I want a frame that holds one word. It doesn't have to explain me.",
	"询问空框": "Ask about the empty frame",
	"空框为什么比装进去的字更容易被人记住？": "Why is the empty frame easier to remember than the word inside it?",
	"暂不交易": "Leave",
	"我先保留手里的字，等它愿意进入一个边界。": "I'll keep the word until it is ready to enter a boundary.",
	"按遗产交易": "Trade with the legacy",
	"我会带上旧句子，但梗框里只放今天拾到的字。": "I'll carry the old sentence, but the frame will hold only the word I found today.",
	"质疑价格": "Challenge the price",
	"遗产已经替我说过一次，为什么还要支付第二次价格？": "The legacy has already spoken for me once. Why must I pay a second price?",
	"拒绝附言": "Refuse the attachment",
	"不能不带旧话交易的话，我就让这次交易保持空白。": "If I can't trade without old words, I'll leave this transaction blank.",
	"签字购买": "Sign and buy",
	"购买者和说话者暂时是同一个人，我愿意在这里签字。": "For now, the buyer and the speaker are the same person. I'll sign here.",
	"索要表格": "Request a form",
	"请给我一份没有预填答案的申请表。": "Please give me an application with no answers filled in.",
	"撤回申请": "Withdraw",
	"如果签名会替我继续说话，我撤回这次购买。": "If the signature will keep speaking for me, I withdraw the purchase.",
	"加入交换": "Join the exchange",
	"我给出一句没有旋律的话，只换一个安静的梗框。": "I'll give you a sentence without a melody. I only want one quiet frame.",
	"询问价格歌": "Ask about the price-song",
	"价格唱完以后消失了，我该把钱交给哪个音？": "The price vanished when the song ended. Which note should I pay?",
	"退出合唱": "Leave the choir",
	"我不想让交易变成副歌，今天先不买。": "I don't want this trade to become a refrain. I won't buy today.",
	"买": "Buy",
	"我 / 买 / 一个 / 空框。": "I / WILL BUY / ONE / EMPTY FRAME.",
	"看空手": "Look at the empty hand",
	"你 / 手里 / 已经 / 有 / 我的东西吗。": "DO / YOU / ALREADY / HAVE / SOMETHING OF MINE?",
	"留下": "Leave it",
	"字 / 留下 / 我 / 走。": "THE WORD / STAYS / I / GO.",

	# Communication items, ending choices, prologue, and epilogue.
	"哈": "HA",
	"吉": "JI",
	"米": "MI",
	"静音贴": "Mute Patch",
	"现实句子严重失真时，临时压低 18% 的污染噪声。": "When a reality sentence is badly distorted, temporarily reduce corruption noise by 18%.",
	"语义锚": "Semantic Anchor",
	"现实句子严重失真时，临时压低 14% 的污染噪声。": "When a reality sentence is badly distorted, temporarily reduce corruption noise by 14%.",
	"旧词典页": "Old Dictionary Page",
	"仅能使用一次，但会压低 32% 的污染噪声。": "One use only; reduce corruption noise by 32%.",
	"空白": "Blank",
	"（空白）": "(blank)",
	"（先确认一件事。你手里拿着什么？）": "(First, let's confirm one thing. What are you holding?)",
	"一部没有信号的手机。它在我醒来以前就亮着。": "A phone with no signal. It was lit before I woke up.",
	"（你在等谁的消息？）": "(Whose message are you waiting for?)",
	"不。我在等路面停止向后移动。它每退一步，塔就多出一层。": "No. I'm waiting for the road to stop moving backward. Every step it slips back adds another floor to the tower.",
	"城市广播说今天一切正常。广播重复了七次，正常因此变成一个可疑的词。": "The city broadcast says everything is normal today. It repeated itself seven times, which made normal a suspicious word.",
	"（从哪里开始？）": "(Where do we begin?)",
	"从一个字开始。先让它进入框里，再看它会把谁赶出去。": "With one word. Put it in the frame first, then see whom it pushes out.",
	"所有遗产规则都说智者住在这里。这里没有智者。": "Every Legacy Rule says the wise one lives here. There is no wise one here.",
	"塔顶只有一台没有接线的发射机。指示灯按照你的呼吸闪烁。": "At the top is only an unwired transmitter. Its indicator blinks in time with your breathing.",
	"（它在发送什么？）": "(What is it transmitting?)",
	"你把耳朵贴近外壳。里面传来整座城市的声音，每个人都在准确重复别人。": "You press your ear to the casing. The whole city is inside; everyone is repeating someone else perfectly.",
	"你想说一句普通的话。每一层却先替你开口。": "You try to say something ordinary. Every floor speaks before you can.",

	# Dynamic feedback and fallback labels. Placeholders must remain intact.
	"街区遗物": "Street Relic",
	"拾取街区遗物：%s。%s": "Street relic collected: %s. %s",
	"信号已经写入。": "Signal recorded.",
	"你打算说什么？": "What will you say?",
	"%s移开了视线。": "%s looked away.",
	"对方没有马上回答。": "They did not answer right away.",
	"你从信号商人那里买到%s，可用 %d 次。": "You bought %s from the Signal Merchant. Uses available: %d.",
	"沟通辅助": "Communication Aid",
	"%s ×%d": "%s ×%d",
	"今天已经没有能说出口的行动。": "No actions remain today that can be spoken aloud.",
	"（%s生效，剩余 %d 次）": "(%s activated; %d uses remaining)",
	"对方把一个梗框留在你手边。框沿没有商人的价签。": "They left a Meme Frame beside your hand. Its edge bore no merchant's price tag.",
	"保底": "Guaranteed",
	"概率命中": "Random roll succeeded",
	"现实交流奖励：获得一个梗框（%s）。": "Reality conversation reward: Meme Frame acquired (%s).",
	"梗框": "Meme Frame",
	"你买到一个梗框。它只能容纳一个字。": "You bought a Meme Frame. It can hold only one word.",
	"放入一个字": "Insert one word",
	"梗字「%s」": "Meme Word: %s",
	"复合「%s」": "Compound: %s",
	"两个旧梗粘在一起。新梗更响，也更脏。": "Two old memes fused. The new meme is louder, and dirtier.",
	"牌型完成：%s，整数倍率 +%d。": "Pattern complete: %s. Multiplier +%d.",
	"未知牌型": "Unknown Pattern",
	"街区遗物结算：%s。": "Street relics applied: %s.",
	"第 %d 层留下遗产规则：%s": "Floor %d left behind a Legacy Rule: %s",
	"仍能认出你": "They can still recognize you",
	"句子留下裂痕": "The sentence left a crack",
	"只剩熟悉的语气": "Only a familiar tone remains",
	"彼此已无法确认": "Neither of you can recognize the other",
	"第 %d 层许可：%s": "Floor %d permit: %s",
	"永久修正": "Permanent Modifier",
	"塔": "TOWER",
	"哈吉米 ": "Hajimi ",
	"来源被动": "Source Passive",
	"永久许可": "Permanent Permit",
	"未命名牌型": "Unnamed Pattern",
	"%d/%d 今日风向": "%d/%d today's trends",
	"%d/%d 隐藏标签": "%d/%d hidden tags",
	"%d/%d 字": "%d/%d words",
	"%d/%d 必要标签": "%d/%d required tags",
	"%d/%d 复读 · %s": "%d/%d repeats · %s",
	"标签命中": "tag matched",
	"缺反问/禁问": "missing Counterquestion or Forbidden Question",
	"第二天，巴别塔把你标记到第 %d 层。": "The next day, the Tower of Babel marked you for Floor %d.",
	"第二天，楼层退回第 %d 层，但遗产规则没有消失。": "The next day, you were sent back to Floor %d, but the Legacy Rules remained.",
	"第二天，塔没有移动，只是把门槛悄悄放低。": "The next day, the tower did not move. It only lowered the threshold in silence.",
	"第 %d 天，塔强制收录你到第 %d 层。": "On Day %d, the tower forcibly registered you on Floor %d.",
	"第 %d 层开放三项许可，必须保留其中一项。": "Floor %d opened three permits. You must keep one.",

	# Reality-floor pickups and actors.
	"信号筹码": "Signal Token",
	"下一次发布的传播基础 +8。": "Next post: base reach +8.",
	"回声镜片": "Echo Lens",
	"下一次发布的整数倍率 +1。": "Next post: multiplier +1.",
	"清晰线": "Clarity Thread",
	"立即恢复 7 点清晰。": "Restore 7 Clarity immediately.",
	"信号商人": "Signal Merchant",
	"迟到者": "Latecomer",
	"回声住户": "Echo Resident",
	"抄写员": "Copyist",
	"无名信徒": "Nameless Believer",
	"旧帖目击者": "Old-Post Witness",

	# Non-Chinese visible residue emitted by the same state data.
	"■■■■": "■■■■",
	"■ ■ ■ ■": "■ ■ ■ ■",
	"……": "...",
	"■": "■",
	"▦": "▦",
	"∴": "∴",
	"//": "//",
	"□": "□",
}


const JA: Dictionary = {
	# Tags, signal patterns, tarot, and reusable sentence blocks.
	"哈吉米": "ハジミ",
	"追问": "追加質問",
	"日常": "日常",
	"空位": "空席",
	"沉默": "沈黙",
	"巴别塔": "バベルの塔",
	"信徒": "信徒",
	"刷新": "更新",
	"反问": "問い返し",
	"禁问": "禁問",
	"圣歌": "聖歌",
	"双声回路": "二声回路",
	"命中至少 2 个今日风向": "本日のトレンドを2つ以上満たす",
	"杂讯列阵": "雑音アレイ",
	"成品含至少 4 种隐藏标签": "隠しタグを4種類以上含む",
	"独字成句": "一字成句",
	"发布一个只含 1 个字的基础梗": "一文字だけの基本ミームを投稿する",
	"空位对子": "空席ペア",
	"同时含有「空位」和「沉默」": "空席と沈黙を含める",
	"巴别直线": "バベル・ストレート",
	"集齐「巴别塔」「信徒」「圣歌」": "バベルの塔・信徒・聖歌を揃える",
	"禁问回环": "禁問ループ",
	"复读一次并带有反问或禁问": "一度反復し、問い返しか禁問を含める",
	"星星": "星",
	"命中至少 2 个风向时，整数倍率额外 +1。": "トレンドを2つ以上満たすと、倍率がさらに+1。",
	"太阳": "太陽",
	"每次发布获得额外 14 点传播基础。": "投稿ごとに基礎拡散力+14。",
	"月亮": "月",
	"污染达到 40% 时，传播基础 +16。": "汚染が40%以上のとき、基礎拡散力+16。",
	"隐者": "隠者",
	"第一次复用相同表达不触发衰减。": "同じ表現を初めて再使用するとき、反復減衰を無視する。",
	"高塔": "塔",
	"融合梗的整数倍率额外 +1。": "融合ミームの倍率+1。",
	"倒吊人": "吊るされた男",
	"每条遗产造成的隐性交流损耗减少 4。": "遺産ルール1件あたりの会話ペナルティを4軽減する。",
	"审判": "審判",
	"今日牌型成立时再获得 18 点传播基础。": "本日のパターン成立時、基礎拡散力+18。",
	"不分昼夜": "昼夜を問わず",
	"每天多 1 次行动。": "1日の行動回数+1。",
	"星坠高塔": "星降る塔",
	"融合梗的整数倍率再 +1。": "融合ミームの倍率がさらに+1。",
	"月下隐者": "月下の隠者",
	"额外忽略 1 次复读衰减。": "反復減衰をさらに1回無視する。",
	"我": "私は",
	"想": "～したい",
	"正常": "きちんと",
	"说明": "説明する",
	"这件事": "このことを",
	"不是": "～ではない",
	"那个意思": "そういう意味",
	"请": "お願い",
	"听我": "私の話を聞いて",
	"说完": "最後まで話させて",
	"哈吉米，必须补票": "ハジミ、運賃を精算しなければならない",
	"在线本身就是发言": "オンラインでいること自体が発言だ",
	"请用更新后的句式进入": "更新後の文型で入場してください",
	"你为什么需要他说话": "なぜ、その人に話してもらう必要があるのですか？",

	# Generic reality responses.
	"直接说明": "率直に説明する",
	"我只是想把刚才的事情说清楚。": "さっきのことを、きちんと説明したいだけです。",
	"先道歉": "先に謝る",
	"对不起，我没有想让你觉得被忽视。": "ごめんなさい。無視されたと思わせるつもりはなかった。",
	"请你再说": "もう一度言ってもらう",
	"请你再说一遍，我想认真听完。": "もう一度言ってください。最後まできちんと聞きたい。",
	"询问商品": "商品について尋ねる",
	"我想看看能帮助沟通的东西。": "意思疎通を助けるものを見せてほしい。",
	"说明来意": "用件を伝える",
	"我需要让别人更容易听懂我。": "もっと伝わりやすくするものが必要です。",
	"试探价格": "値段を確かめる",
	"这些东西分别需要多少钱？": "それぞれいくらですか？",

	# Reality floor 1.
	"你也在等那班已经经过、但谁都没看见的车吗？": "誰にも見られないまま、もう通り過ぎたあのバスを、あなたも待っているの？",
	"迟到者看了一眼空荡荡的站牌，像是在替它保守秘密。": "遅刻者は人けのないバス停に目をやった。まるで、その秘密を守っているようだった。",
	"一起等": "一緒に待つ",
	"我没有看见那班车，但我可以陪你再等一会儿。": "あのバスは見なかったけれど、もう少しなら一緒に待てる。",
	"核对时间": "時刻を確かめる",
	"站牌上的时间没有变，也许车还没有真正经过。": "標識の時刻は変わっていない。まだ本当には通り過ぎていないのかもしれない。",
	"先离开": "ここを離れる",
	"如果下一班也没有声音，我们就沿着路走回去。": "次のバスも音を立てなければ、道を歩いて戻ろう。",
	"楼上的水管昨晚喊了我的名字。你住哪一户？": "昨夜、上の階の水道管が私の名前を呼んだ。あなたはどの部屋に住んでいる？",
	"回声住户把钥匙攥紧了一点，管道在墙里轻轻敲了三下。": "こだまの住人は鍵を少し強く握った。壁の中で配管が軽く三度鳴った。",
	"说出住处": "住まいを答える",
	"我住在路尽头那扇总是关不严的门后面。": "道の突き当たりにある、いつもきちんと閉まらない扉の向こうに住んでいる。",
	"问水管": "水道管について尋ねる",
	"也许水管只是记住了你每天回家的脚步声。": "配管は、あなたが毎日帰ってくる足音を覚えただけかもしれない。",
	"确认名字": "名前を確かめる",
	"它喊的是你的名字，还是住在这里的每一个名字？": "呼んだのはあなたの名前？ それとも、ここに住むすべての名前？",
	"我把门牌抄了三遍，每一遍都少一个人。你能替我数吗？": "表札を三度書き写した。どれも一人ずつ足りない。代わりに数えてくれる？",
	"抄写员没有递出纸，只把空着的第四行折进掌心。": "写字係は紙を渡さず、空白の四行目だけを掌に折り込んだ。",
	"重新数": "数え直す",
	"我们从第一扇门开始，名字和门牌分开数。": "最初の扉から始めて、名前と表札を別々に数えよう。",
	"保留空行": "空行を残す",
	"少掉的人也许需要一个空位置，而不是另一个名字。": "いなくなった人に必要なのは、別の名前ではなく空の場所かもしれない。",
	"停止抄写": "書写を止める",
	"先别写第四遍，纸可能正在学习怎样删掉人。": "四度目はまだ書かないで。紙が人の消し方を覚えかけている。",
	"你刚才抬头了吗？塔上掉下来一片像收据的云。": "さっき上を見た？ 塔から、領収書みたいな雲が一枚落ちてきた。",
	"无名信徒把那片不存在的纸塞进口袋，动作十分熟练。": "名もなき信徒は、存在しないその紙を手慣れた動きでポケットにしまった。",
	"描述天空": "空を描写する",
	"我只看见绿色的天，云上没有价格，也没有日期。": "見えたのは緑の空だけ。雲には値段も日付もなかった。",
	"索要收据": "領収書を求める",
	"如果它真是收据，上面应该写着是谁买下了这座塔。": "本当に領収書なら、誰がこの塔を買ったのか書いてあるはずだ。",
	"看着地面": "地面を見る",
	"我没有抬头，我怕地面趁机换掉回去的方向。": "上は見なかった。隙を見て地面が帰り道を入れ替えそうだったから。",
	"我在十年前的帖子里看见今天的你。那是你吗？": "十年前の投稿に、今日のあなたが写っていた。あれはあなた？",
	"旧帖目击者没有展示截图，屏幕却自行亮了一瞬。": "旧投稿の目撃者はスクリーンショットを見せなかった。それでも画面は一瞬ひとりでに点いた。",
	"承认": "認める",
	"如果照片里的我正在等今天，那个人也可以算是我。": "写真の私が今日を待っているのなら、あの人も私ということにできる。",
	"否认": "否定する",
	"十年前我不在这里，帖子也不该记得我的脸。": "十年前、私はここにいなかった。投稿が私の顔を覚えているはずもない。",
	"留下回复": "返信を残す",
	"请替我回复一句，让过去不要继续往前翻页。": "代わりに一言返信して。過去がこれ以上、先へスクロールしないように。",

	# Reality floor 2.
	"先说上一层留下的那句话，再告诉我你为什么迟到。顺序不能反。": "先に下の階が残した言葉を言い、それから遅れた理由を話して。順番を逆にしてはいけない。",
	"迟到者认真听完规定的部分，剩下的话被风带到很远。": "遅刻者は規定された部分を注意深く聞き、残りの言葉は風に遠く運ばれた。",
	"照顺序说": "順番どおりに話す",
	"我会先念完遗产，然后说明路口为什么没有放我过去。": "先に遺産を読み終え、それから交差点が通してくれなかった理由を説明する。",
	"先说理由": "理由を先に話す",
	"我迟到是因为那条路反复把我送回同一块路牌。": "同じ標識へ何度も送り返す道のせいで遅れた。",
	"拒绝顺序": "順番を拒む",
	"如果原因只能排在旧话后面，它就不再是我的原因。": "理由が古い言葉の後にしか置けないなら、それはもう私の理由ではない。",
	"这层每户都要保管一句旧话。我家的那句半夜会自己换位置。": "この階では各戸が古い言葉を一つ保管する。うちの言葉は夜中に勝手に場所を変える。",
	"回声住户点了点头，像是刚完成一次例行点名。": "こだまの住人は、いつもの点呼を終えたようにうなずいた。",
	"锁住它": "閉じ込める",
	"把那句话写在门背后，也许它就找不到新的房间。": "扉の裏に書けば、新しい部屋を見つけられないかもしれない。",
	"记录移动": "移動を記録する",
	"今晚记下它每次换位置的时间，不要改动其中的字。": "今夜、場所を変えた時刻をすべて記録して。言葉は変えないで。",
	"送回楼下": "下へ返す",
	"旧话来自上一层，我们可以沿楼梯把它送回原处。": "古い言葉は下の階から来た。階段を使って元へ戻せる。",
	"登记表说你已经回答过了。可我这里还是空白。": "登録簿では、あなたはもう答えたことになっている。でも私の欄はまだ空白だ。",
	"抄写员在空白处盖章，印泥发出一声很轻的叹息。": "写字係が空白に判を押すと、朱肉が小さくため息をついた。",
	"再回答": "もう一度答える",
	"我可以再说一次，但请保留这次说话留下的空白。": "もう一度言える。でも今回の言葉が残す空白は、そのままにして。",
	"质疑记录": "記録を疑う",
	"表格记住的是动作，不一定记住了我真正说过什么。": "用紙が覚えているのは動作で、実際に話した内容とは限らない。",
	"请求盖章": "押印を求める",
	"请先证明这里曾经空着，再把我的句子写进去。": "まず、ここが空白だったことを証明して。それから私の文を書き込んで。",
	"我们不再问你叫什么。我们只核对你携带了哪一句遗产。": "もう名前は尋ねない。どの遺産を持っているかだけ確認する。",
	"无名信徒在听见遗产时微笑，在听见其余内容时闭上眼睛。": "名もなき信徒は遺産を聞くと微笑み、それ以外の言葉には目を閉じた。",
	"坚持名字": "名前を通す",
	"遗产跟着我，但我的名字仍然应该先于它出现。": "遺産は私についてくる。それでも私の名前が先に現れるべきだ。",
	"出示遗产": "遺産を示す",
	"我带着上一层最响的句子，它比我更容易被认出来。": "下の階で最も響いた言葉を持っている。私よりそちらのほうが見分けやすい。",
	"声称空手": "何も持っていないと申告する",
	"我想试着什么都不携带，只用今天剩下的词站在这里。": "何も持たず、今日残った言葉だけでここに立ってみたい。",

	# Reality floor 3.
	"请提交一句未被使用过的自己。重复部分将退回上一窗口。": "未使用のあなたを一文、提出してください。重複部分は前の窓口へ返送されます。",
	"迟到者撕下回执，纸的背面印着同一张回执。": "遅刻者が控えを切り取ると、裏面にも同じ控えが印刷されていた。",
	"提交原句": "オリジナルの文を提出する",
	"这句话只在现在出现，请不要替它补上以前的编号。": "この文は今だけ存在する。以前の番号を付け足さないで。",
	"承认重复": "反復を認める",
	"我借用了旧句子的结构，但其中的犹豫是今天才有的。": "古い文の構造を借りた。でも、このためらいは今日生まれた。",
	"寻找窗口": "窓口を探す",
	"上一窗口已经封死，我只能把退件留在这里。": "前の窓口は閉鎖されている。返却物はここに置くしかない。",
	"你所在的住处已被归类为比喻。实体住址需要另行申请。": "あなたの住居は比喩に分類されました。実在する住所には別途申請が必要です。",
	"回声住户把申请表对折，折痕恰好穿过自己的地址。": "こだまの住人は申請書を二つ折りにした。折り目は正確に自分の住所を横切った。",
	"申报实体": "実在を申告する",
	"我的房间有墙和门，也有一盏会在凌晨熄灭的灯。": "部屋には壁と扉があり、明け方に消える灯りもある。",
	"接受比喻": "比喩を受け入れる",
	"如果住处只是比喻，请注明我究竟被比作了什么。": "住居が比喩にすぎないなら、私は何にたとえられたのか明記して。",
	"撤销地址": "住所を取り消す",
	"取消我的地址吧，这样回去的时候就不会再次走错。": "住所を取り消して。そうすれば帰るとき、もう道を間違えない。",
	"缺失人员栏不能留空。请填写一个仍然存在的人。": "行方不明者の欄は空白にできません。まだ存在する人を記入してください。",
	"抄写员将答案归档，抽屉里传来某个人翻身的声音。": "写字係が回答を保管すると、引き出しの中で誰かが寝返りを打った。",
	"填写自己": "自分の名前を記入する",
	"先写我的名字，至少此刻我还站在表格外面。": "まず私の名前を書いて。少なくとも今は、まだ用紙の外に立っている。",
	"保留缺失": "不在を残す",
	"缺失不是空白，它是一个人离开后留下的准确形状。": "不在は空白ではない。人が去ったあとに残る、正確な形だ。",
	"询问抽屉": "引き出しについて尋ねる",
	"请打开抽屉，里面的人也许知道自己是否仍然存在。": "引き出しを開けて。中の人なら、自分がまだ存在するか知っているかもしれない。",

	# Reality floors 4 and 5.
	"我们唱到你的名字时，请不要回答。回答会破坏和声。": "あなたの名前を歌うとき、返事をしないで。返事は和声を壊す。",
	"合唱没有停下，只在主角应该出现的位置稍微变调。": "合唱は止まらず、主人公が入るはずだった箇所だけ少し音程がずれた。",
	"保持沉默": "沈黙する",
	"我会让名字从我身边经过，不把它认领回来。": "名前を私のそばに通らせ、取り戻さない。",
	"打断合唱": "合唱を遮る",
	"那是我的名字，它不该只作为你们旋律里的一个音。": "それは私の名前だ。あなたたちの旋律の一音だけであってはいけない。",
	"轻声跟唱": "小さく歌う",
	"我只跟着最后一个音，不唱名字，也不唱塔。": "最後の一音だけをなぞる。名前も塔も歌わない。",
	"圣歌需要一个空位。大家一致认为那个位置很像你。": "聖歌には空席が一つ必要だ。全員が、その場所はあなたによく似ていると言っている。",
	"无名信徒向旁边挪开半步，空位却仍然跟着主角。": "名もなき信徒が半歩よけても、空席は主人公についてきた。",
	"站进空位": "空いた場所に立つ",
	"我可以站在那里，但不会把沉默假装成赞同。": "そこに立つことはできる。でも沈黙を同意のふりにはしない。",
	"拒绝位置": "拒む",
	"像我不等于属于我，请把那个位置继续空着。": "私に似ていても、私のものとは限らない。そのまま空けておいて。",
	"询问缺席者": "欠席者について尋ねる",
	"这个空位原来属于谁，你们为什么不再唱那个人？": "この空席は誰のものだった？ なぜもう、その人を歌わない？",
	"你 / 还 / 把 / 自己 / 带着吗": "あなたは / まだ / 自分を / 連れて / いるの",
	"迟到者的嘴唇动了五次，只有斜线抵达空气。": "遅刻者の唇は五度動いた。空気まで届いたのは斜線だけだった。",
	"仍在这里": "まだここにいる",
	"我还在这里，只是句子比我先到了一步。": "私はまだここにいる。ただ文のほうが一歩先に着いただけ。",
	"遗失一部分": "一部を失った",
	"有一部分留在楼下，正在替我继续回答问题。": "一部は下の階に残り、今も代わりに質問へ答えている。",
	"逐字确认": "一文字ずつ確かめる",
	"我会一个字一个字地数，数到停下的地方就是我。": "一文字ずつ数える。止まった場所が私だ。",
	"窗 / 外 / 有 / 一只 / 没有过去的鸟": "窓 / の外に / 一羽の / 通り過ぎなかった / 鳥",
	"旧帖目击者望向窗外。那里没有窗，鸟仍然飞过了一次。": "旧投稿の目撃者は外を見た。そこに窓はなかったが、鳥は一度だけ通り過ぎた。",
	"描述那只鸟": "鳥を描写する",
	"它没有向前飞，只让身后的世界不断离开。": "前へは飛ばず、背後の世界だけを遠ざけ続けている。",
	"寻找窗户": "窓を探す",
	"先找到窗户吧，不然我们不知道外面究竟属于哪里。": "まず窓を見つけよう。そうしないと、外がどこに属するのかわからない。",
	"发送信号": "信号を送る",
	"如果它没有过去，就让这句话追上它，替我们问候一次。": "通り過ぎなかったのなら、この文に追いつかせ、代わりに挨拶させよう。",

	# Extended reality conversations.
	"站牌忽然显示“无信号”。可这条街从来没有接入过线路。你还要等吗？": "停留所の表示が突然「圏外」になった。でも、この通りには最初から回線などない。それでも待つ？",
	"迟到者把手机举向塔影，屏幕上的叉号短暂变成一扇门。": "遅刻者は携帯電話を塔の影へ掲げた。画面の×印が一瞬、扉に変わった。",
	"继续等候": "待ち続ける",
	"再等一班吧；没有线路，不等于没有人正试着抵达。": "もう一本待とう。回線がないからといって、誰もたどり着こうとしていないとは限らない。",
	"追查塔影": "塔の影を追う",
	"信号也许不是从天上消失，而是被塔一层层收走了。": "信号は空から消えたのではなく、塔が一階ずつ回収したのかもしれない。",
	"沿路步行": "道を歩く",
	"我们顺着遗产标记走，看看旧句子把终点改到了哪里。": "遺産の印をたどり、古い文が終点をどこへ書き換えたのか見に行こう。",
	"车终于来了。报站器只念上一层留下的梗，不再念地名。你在哪里下车？": "ようやくバスが来た。車内放送は下の階が残したミームだけを読み上げ、地名を言わない。どこで降りる？",
	"迟到者在没有地名的一站按铃。车门打开，塔的影子没有跟下来。": "遅刻者は地名のない停留所でボタンを押した。扉が開いても、塔の影は降りてこなかった。",
	"遗产之后": "遺産のあと",
	"等它念完遗产，我要在第一个属于今天的停顿下车。": "遺産を読み終えたら、今日に属する最初の間で降りる。",
	"沉默站点": "沈黙の停留所",
	"没有报站声的地方就是我的站，至少那里还没有被命名。": "放送がない場所が私の停留所だ。少なくとも、そこはまだ名付けられていない。",
	"留在车上": "車内に残る",
	"我先不下车，直到有人用自己的话说出一个方向。": "誰かが自分の言葉で行き先を告げるまで、まだ降りない。",
	"报站声被污染成连续的旧梗。迟到者捂住听筒，车还没有来，谈话先驶远了。": "案内放送は汚染され、古いミームの連なりになった。遅刻者が受話口を押さえる。バスより先に、会話が遠ざかっていった。",
	"墙里的回声开始替我们回答，而且每次都比原话多一句遗产。要把哪一句留下？": "壁の中のこだまが私たちの代わりに答え始めた。しかも毎回、元の言葉より遺産が一文多い。どの文を残す？",
	"回声住户贴近墙面，听见自己的声音从更高一层缓慢返回。": "こだまの住人が壁へ耳を寄せると、自分の声が上の階からゆっくり戻ってきた。",
	"留下原话": "元の言葉を残す",
	"只留下我们刚才说的句子，遗产可以经过，但不要冒充回声。": "今話した文だけを残そう。遺産が通るのはかまわないが、こだまのふりはさせない。",
	"标记遗产": "遺産に印を付ける",
	"把多出来的旧话标上楼层，让它不能假装今天才出生。": "増えた古い言葉に階数を記し、今日生まれたふりができないようにする。",
	"关闭管道": "配管を閉じる",
	"先关掉这段管道，沉默也比被替写的回答更诚实。": "まずこの配管を閉じよう。上書きされた答えより、沈黙のほうが正直だ。",
	"水龙头流出一串陌生口音。住户说这就是语言污染的味道。你怎么确认还是水？": "蛇口から見知らぬ訛りが連なって流れ出す。住人は、これが言語汚染の味だと言う。まだ水だと、どう確かめる？",
	"回声住户接住一滴无声的水。它没有复述任何人，钥匙终于松开。": "こだまの住人は音のない一滴を受け止めた。それは誰の言葉も繰り返さず、ようやく鍵を握る手が緩んだ。",
	"观察倒影": "映り込みを見る",
	"如果倒影还会被波纹打断，它至少没有完全变成一句口号。": "映り込みが波紋に遮られるなら、少なくとも完全に標語にはなっていない。",
	"尝试命名": "名付けてみる",
	"先叫它水一次；如果它立刻要求复读，我们就换一个杯子。": "一度だけ水と呼ぼう。すぐ復唱を求めてきたら、別のコップに替える。",
	"保持无名": "名を付けない",
	"不急着命名，让它在语言找到之前先作为液体留下。": "急いで名付けず、言葉に見つかるまでは液体のまま残しておく。",
	"管道抢先说完所有答案。回声住户关上阀门，墙里仍有人继续这场谈话。": "配管がすべての答えを先に言い切った。こだまの住人が弁を閉じても、壁の中では誰かが会話を続けていた。",
	"档案柜要求给你的每句话填写“遗产来源”。原创一栏已经被涂黑。你填什么？": "書庫棚は、あなたの文すべてに「遺産の出典」を記入するよう求めている。「オリジナル」の欄は黒く塗りつぶされている。何を書く？",
	"抄写员把表格转过来，背面密密麻麻都是尚未发生的引用。": "写字係が用紙を裏返す。裏面は、まだ起きていない引用で埋め尽くされていた。",
	"填写此刻": "今この時を書く",
	"来源写此刻；这句话也许借过词，但犹豫是我自己的。": "出典は今この時。この文は言葉を借りていても、ためらいは私のものだ。",
	"拒绝来源": "出典を拒む",
	"我不替活着的话伪造祖先，请把这一栏保持空白。": "生きている言葉の祖先を捏造したくない。この欄は空白のままにして。",
	"登记污染": "汚染を記録する",
	"标注语言污染；相似不一定是继承，也可能是感染。": "言語汚染と記して。似ているからといって継承とは限らない。感染かもしれない。",
	"盖章机说，未被塔收录的句子不算存在。抄写员把印章递给你。": "押印機は、塔に収録されていない文は存在しないと言う。写字係が印章を差し出した。",
	"抄写员收回没有落下的印章，把你的句子夹进两页制度之间。": "写字係は押されなかった印章を引き取り、あなたの文を二頁の制度の間に挟んだ。",
	"不盖印章": "印を押さない",
	"存在不该由塔批准；让这句话带着空白离开档案。": "存在を塔の許可に委ねるべきではない。この文を空白ごと書庫から出そう。",
	"盖在边缘": "端に押す",
	"只盖在纸的边缘，证明制度碰过它，却没有拥有它。": "紙の端にだけ押し、制度が触れはしたが、所有してはいないと示す。",
	"改写条款": "条項を書き換える",
	"先把条款改成“说出即存在”，再决定是否需要印章。": "まず条項を「語られたものは存在する」に変え、それから印章が必要か決める。",
	"盖章机吞掉了句子的主语。抄写员拉下断电杆，本次登记以空白中止。": "押印機が文の主語を飲み込んだ。写字係は電源レバーを下ろし、今回の登録は空白のまま中断された。",
	"塔里的发射机没有接线，信徒却说每晚都能收到圣歌。你认为声音从哪里来？": "塔の送信機には配線がない。それでも信徒は毎晩、聖歌を受信すると言う。音はどこから来ると思う？",
	"无名信徒仰头辨认那段旋律，塔窗一层接一层地亮错顺序。": "名もなき信徒は顔を上げ、旋律を聞き分けようとした。塔の窓が階ごとに、間違った順番で灯った。",
	"来自人群": "群衆から",
	"也许是人群在塔下互相复述，最后忘了第一句话属于谁。": "塔の下で群衆が互いの言葉を繰り返し、最初の一文が誰のものか忘れたのかもしれない。",
	"来自遗产": "遺産から",
	"遗产梗会自己寻找嗓子，圣歌只是它们同时借到人的时刻。": "遺産ミームは自分で声を探す。聖歌とは、それらが同時に人の喉を借りる瞬間だ。",
	"来自静电": "静電気から",
	"没有信号时，静电也会被当成启示；先别急着跪下。": "圏外なら、雑音さえ啓示に見える。まだひざまずかないで。",
	"信徒请你献出一句不会污染别人的话，作为进入上层的圣歌。": "信徒は、他人を汚染しない一文を、上の階へ入るための聖歌として捧げてほしいと言う。",
	"无名信徒没有唱你的句子，只把它安静地留在门外。塔门第一次自己开了。": "名もなき信徒はあなたの文を歌わず、静かに扉の外へ残した。塔の扉が初めて、ひとりでに開いた。",
	"保留疑问": "問いを残す",
	"我只能献出一个问题：我们是否允许别人不回答。": "捧げられるのは一つの問いだけ。私たちは、他人が答えないことを許せるだろうか。",
	"归还名字": "名前を返す",
	"把每个人的名字还给本人，不把它们编进共同的副歌。": "一人ひとりの名前を本人へ返し、皆の副歌に編み込まない。",
	"献出停顿": "間を捧げる",
	"我献出一句话结束后的停顿，让下一人有地方开口。": "文が終わったあとの間を捧げる。次の人が口を開ける場所になるように。",
	"圣歌突然只剩同一个梗。无名信徒停止合唱，塔门在污染扩散前合上。": "聖歌は突然、同じミームだけになった。名もなき信徒は合唱を止め、汚染が広がる前に塔の扉を閉じた。",
	"旧帖显示这里“信号满格”，可所有回复都写着十年后发送。你要点开哪一条？": "旧投稿には「電波良好」と表示されているのに、返信はすべて送信日時が十年後になっている。どれを開く？",
	"旧帖目击者滑动屏幕，日期栏像坏掉的电梯一样上下跳动。": "旧投稿の目撃者が画面を滑らせると、日付欄は壊れたエレベーターのように上下した。",
	"最早回复": "最初の返信",
	"打开最早的一条，看看是谁先把未来误认成了遗产。": "最初の一件を開き、誰が真っ先に未来を遺産と見間違えたのか確かめる。",
	"未发回复": "未送信の返信",
	"打开那条尚未发送的，也许它还来得及换一种说法。": "まだ送られていない一件を開く。今なら別の言い方に間に合うかもしれない。",
	"关闭帖子": "投稿を閉じる",
	"先关掉帖子；无信号时，时间不该假装自己已经上传。": "まず投稿を閉じよう。圏外のとき、時間までアップロード済みのふりをするべきではない。",
	"最后一条回复只有一个梗框，里面空着。帖子问：要把今天的哪个词留给过去？": "最後の返信には、空のミーム枠が一つあるだけ。投稿が尋ねる。今日のどの言葉を過去へ残す？",
	"旧帖目击者没有截屏。空框自行保存，又把今天完整地退还给你。": "旧投稿の目撃者はスクリーンショットを撮らなかった。空の枠はひとりでに保存され、今日を丸ごとあなたに返した。",
	"留下存在": "存在を残す",
	"留下“存在”；过去需要知道我们没有只活成引用。": "「存在」を残す。私たちは引用としてだけ生きたのではないと、過去に知らせたい。",
	"留下无信号": "圏外を残す",
	"留下“无信号”；让未来明白沉默也可能是线路断了。": "「圏外」を残す。沈黙は回線が切れただけかもしれないと、未来に伝える。",
	"什么不留": "何も残さない",
	"什么都不留；过去不该提前继承我们尚未说完的话。": "何も残さない。まだ話し終えていない言葉を、過去が先に継承するべきではない。",
	"帖子开始自动复制你尚未说出的词。旧帖目击者拔掉电源，屏幕仍亮在中断处。": "投稿が、あなたのまだ口にしていない言葉を自動で複製し始めた。旧投稿の目撃者が電源を抜いても、画面は中断箇所で光り続けた。",

	# Signal Merchant dialogue and choices.
	"我卖的是能装住一个字的空框。字会漏出来，框不会。": "一文字を収められる空の枠を売っている。文字は漏れるが、枠は漏れない。",
	"信号商人敲了敲柜台，空框发出比内容更清楚的声音。": "シグナル商人が台を叩くと、空の枠は中身より明瞭な音を立てた。",
	"本层交易必须附上一句遗产。价格不会因此减少。": "この階の取引には遺産を一文添えること。値段は下がらない。",
	"信号商人收走了声音，没有说明它被记在哪一本账里。": "シグナル商人は声を受け取り、どの帳簿に記したかは言わなかった。",
	"请确认购买者与说话者为同一实体。无法确认也可以签字。": "購入者と話者が同一の存在か確認してください。確認できなくても署名は可能です。",
	"信号商人把签名盖在照片上，照片里的人没有动。": "シグナル商人は写真へ署名を押し付けた。写真の人物は動かなかった。",
	"交换也是圣歌。你给出一句，我归还一个更响的空位。": "交換もまた聖歌だ。一文を差し出せば、もっと響く空席を返そう。",
	"信号商人低声唱出价格，数字在最后一个音里消失。": "シグナル商人は値段を低く歌い、数字は最後の音へ消えた。",
	"买 / 卖 / 留下 / 哪一个": "買う / 売る / 残す / どれ",
	"信号商人伸出空手。主角无法判断交易是否已经发生。": "シグナル商人は空の手を差し出した。主人公には、取引がもう済んだのかわからなかった。",
	"询问梗框": "ミーム枠について尋ねる",
	"我想要一个只装一个字的框，它不需要替我解释。": "一文字だけ入る枠がほしい。私の代わりに説明しなくていい。",
	"询问空框": "空の枠について尋ねる",
	"空框为什么比装进去的字更容易被人记住？": "なぜ中の文字より、空の枠のほうが覚えられる？",
	"暂不交易": "取引しない",
	"我先保留手里的字，等它愿意进入一个边界。": "今は文字を手元に置き、境界へ入りたくなるまで待つ。",
	"按遗产交易": "遺産付きで取引する",
	"我会带上旧句子，但梗框里只放今天拾到的字。": "古い言葉は持っていく。でも枠には今日拾った文字だけを入れる。",
	"质疑价格": "価格を疑う",
	"遗产已经替我说过一次，为什么还要支付第二次价格？": "遺産が一度話したのに、なぜ二度目の代金が要る？",
	"拒绝附言": "付言を拒む",
	"不能不带旧话交易的话，我就让这次交易保持空白。": "古い言葉なしで取引できないなら、今回は空白のままにする。",
	"签字购买": "署名して買う",
	"购买者和说话者暂时是同一个人，我愿意在这里签字。": "購入者と話者は今のところ同一人物。ここに署名する。",
	"索要表格": "用紙を求める",
	"请给我一份没有预填答案的申请表。": "回答が記入済みでない申請書をください。",
	"撤回申请": "申請を撤回する",
	"如果签名会替我继续说话，我撤回这次购买。": "署名が私の代わりに話し続けるなら、購入を取り下げる。",
	"加入交换": "交換に加わる",
	"我给出一句没有旋律的话，只换一个安静的梗框。": "旋律のない一文を渡す。静かな枠を一つだけほしい。",
	"询问价格歌": "値段の歌について尋ねる",
	"价格唱完以后消失了，我该把钱交给哪个音？": "歌い終えたら値段が消えた。どの音へ金を渡せばいい？",
	"退出合唱": "合唱を抜ける",
	"我不想让交易变成副歌，今天先不买。": "取引を副歌にしたくない。今日は買わない。",
	"买": "買う",
	"我 / 买 / 一个 / 空框。": "私 / は / 空の枠を / 一つ買う。",
	"看空手": "空の手を見る",
	"你 / 手里 / 已经 / 有 / 我的东西吗。": "あなた / の手には / もう / 私のものが / あるの？",
	"留下": "残す",
	"字 / 留下 / 我 / 走。": "言葉 / は残る / 私 / は行く。",

	# Communication items, ending choices, prologue, and epilogue.
	"哈": "ハ",
	"吉": "ジ",
	"米": "ミ",
	"静音贴": "消音パッチ",
	"现实句子严重失真时，临时压低 18% 的污染噪声。": "現実の文が大きく歪んだとき、汚染ノイズを一時的に18%軽減する。",
	"语义锚": "セマンティック・アンカー",
	"现实句子严重失真时，临时压低 14% 的污染噪声。": "現実の文が大きく歪んだとき、汚染ノイズを一時的に14%軽減する。",
	"旧词典页": "古い辞書の一頁",
	"仅能使用一次，但会压低 32% 的污染噪声。": "1回限りだが、汚染ノイズを32%軽減する。",
	"空白": "空白",
	"（空白）": "（空白）",
	"（先确认一件事。你手里拿着什么？）": "（先に一つ確認しよう。手に何を持っている？）",
	"一部没有信号的手机。它在我醒来以前就亮着。": "圏外の携帯電話。目を覚ます前から画面が点いていた。",
	"（你在等谁的消息？）": "（誰からのメッセージを待っている？）",
	"不。我在等路面停止向后移动。它每退一步，塔就多出一层。": "違う。路面が後ろへ動くのをやめるのを待っている。一歩下がるたび、塔に一階増える。",
	"城市广播说今天一切正常。广播重复了七次，正常因此变成一个可疑的词。": "市の放送は今日もすべて正常だと言った。七度繰り返したせいで、「正常」は疑わしい言葉になった。",
	"（从哪里开始？）": "（どこから始める？）",
	"从一个字开始。先让它进入框里，再看它会把谁赶出去。": "一文字から。まず枠へ入れ、それが誰を追い出すのか見よう。",
	"所有遗产规则都说智者住在这里。这里没有智者。": "すべての遺産ルールは、賢者がここに住むと言っている。ここに賢者はいない。",
	"塔顶只有一台没有接线的发射机。指示灯按照你的呼吸闪烁。": "塔の頂には、配線されていない送信機が一台あるだけ。表示灯はあなたの呼吸に合わせて点滅する。",
	"（它在发送什么？）": "（何を送信している？）",
	"你把耳朵贴近外壳。里面传来整座城市的声音，每个人都在准确重复别人。": "耳を外殻に当てる。中から街全体の声が聞こえる。誰もが誰かの言葉を正確に繰り返している。",
	"你想说一句普通的话。每一层却先替你开口。": "普通のことを一つ言おうとする。だが、すべての階が先に口を開く。",

	# Dynamic feedback and fallback labels. Placeholders must remain intact.
	"街区遗物": "街区の遺物",
	"拾取街区遗物：%s。%s": "街区の遺物を拾った：%s。%s",
	"信号已经写入。": "シグナルが記録された。",
	"你打算说什么？": "何を話す？",
	"%s移开了视线。": "%sは目をそらした。",
	"对方没有马上回答。": "相手はすぐには答えなかった。",
	"你从信号商人那里买到%s，可用 %d 次。": "シグナル商人から%sを買った。使用可能回数：%d。",
	"沟通辅助": "会話補助",
	"%s ×%d": "%s ×%d",
	"今天已经没有能说出口的行动。": "今日はもう、声にできる行動が残っていない。",
	"（%s生效，剩余 %d 次）": "（%sが作動。残り%d回）",
	"对方把一个梗框留在你手边。框沿没有商人的价签。": "相手はあなたの手元にミーム枠を一つ残した。縁には商人の値札がない。",
	"保底": "天井到達",
	"概率命中": "抽選当選",
	"现实交流奖励：获得一个梗框（%s）。": "現実での会話報酬：ミーム枠を1つ獲得（%s）。",
	"梗框": "ミーム枠",
	"你买到一个梗框。它只能容纳一个字。": "ミーム枠を一つ手に入れた。一文字しか入らない。",
	"放入一个字": "一文字を入れる",
	"梗字「%s」": "ミーム字「%s」",
	"复合「%s」": "複合「%s」",
	"两个旧梗粘在一起。新梗更响，也更脏。": "二つの古いミームが貼り合わさった。新しいミームは、より響き、より汚れている。",
	"牌型完成：%s，整数倍率 +%d。": "パターン成立：%s。倍率+%d。",
	"未知牌型": "不明なパターン",
	"街区遗物结算：%s。": "街区の遺物を適用：%s。",
	"第 %d 层留下遗产规则：%s": "第%d階が遺産ルールを残した：%s",
	"仍能认出你": "まだあなたを見分けられる",
	"句子留下裂痕": "言葉がひびを残している",
	"只剩熟悉的语气": "なじみのある口調だけが残った",
	"彼此已无法确认": "もう互いを確かめられない",
	"第 %d 层许可：%s": "第%d階の許可：%s",
	"永久修正": "恒久補正",
	"塔": "塔",
	"哈吉米 ": "ハジミ ",
	"来源被动": "出典パッシブ",
	"永久许可": "恒久許可",
	"未命名牌型": "名称未設定のパターン",
	"%d/%d 今日风向": "%d/%d 本日のトレンド",
	"%d/%d 隐藏标签": "%d/%d 隠しタグ",
	"%d/%d 字": "%d/%d 文字",
	"%d/%d 必要标签": "%d/%d 必須タグ",
	"%d/%d 复读 · %s": "%d/%d 反復 · %s",
	"标签命中": "タグ一致",
	"缺反问/禁问": "問い返し・禁問なし",
	"第二天，巴别塔把你标记到第 %d 层。": "翌日、バベルの塔はあなたを第%d階に登録した。",
	"第二天，楼层退回第 %d 层，但遗产规则没有消失。": "翌日、第%d階へ戻されたが、遺産ルールは消えなかった。",
	"第二天，塔没有移动，只是把门槛悄悄放低。": "翌日、塔は動かず、閾値だけをそっと下げた。",
	"第 %d 天，塔强制收录你到第 %d 层。": "第%d日、塔はあなたを強制的に第%d階へ登録した。",
	"第 %d 层开放三项许可，必须保留其中一项。": "第%d階に三つの許可が開いた。一つを残さなければならない。",

	# Reality-floor pickups and actors.
	"信号筹码": "シグナル・トークン",
	"下一次发布的传播基础 +8。": "次の投稿の基礎拡散力+8。",
	"回声镜片": "こだまのレンズ",
	"下一次发布的整数倍率 +1。": "次の投稿の倍率+1。",
	"清晰线": "明晰の糸",
	"立即恢复 7 点清晰。": "明晰度を7回復する。",
	"信号商人": "シグナル商人",
	"迟到者": "遅刻者",
	"回声住户": "こだまの住人",
	"抄写员": "写字係",
	"无名信徒": "名もなき信徒",
	"旧帖目击者": "旧投稿の目撃者",

	# Non-Chinese visible residue emitted by the same state data.
	"■■■■": "■■■■",
	"■ ■ ■ ■": "■ ■ ■ ■",
	"……": "……",
	"■": "■",
	"▦": "▦",
	"∴": "∴",
	"//": "//",
	"□": "□",
}


static func entries(locale_code: String) -> Dictionary:
	match locale_code.to_lower():
		"en":
			return EN
		"ja":
			return JA
		_:
			return {}
