extends RefCounted


const EN: Dictionary = {
	# Main menu, settings, phone shell, and HUD.
	"继续游戏": "Continue",
	"回到上次离开的位置": "Return to where you left off",
	"暂无自动存档": "No autosave available",
	"新游戏": "New Game",
	"退出游戏": "Quit Game",
	"语言": "Language",
	"选择语言  /  言語を選択  /  CHOOSE LANGUAGE": "CHOOSE LANGUAGE",
	"返回": "Back",
	"设置": "Settings",
	"音量": "Volume",
	"开启 VHS 质感": "Enable VHS Effect",
	"手动保存": "Save Now",
	"已保存当前进度与设置。": "Progress and settings saved.",
	"保存失败，请检查本地写入权限。": "Save failed. Check local write permissions.",
	"退回主画面": "Return to Main Menu",
	"无信号": "No Signal",
	"选择一个窗口": "Choose a window",
	"塔\n楼层档案": "TOWER\nFLOOR ARCHIVE",
	"帖\n信号瀑布": "FEED\nSIGNAL STREAM",
	"店\n梗框商店": "SHOP\nMEME FRAME STORE",
	"本\n语言工坊": "BOOK\nLANGUAGE WORKSHOP",
	"每个 App 会在手机旁打开独立窗口。": "Each app opens in its own window beside the phone.",
	"社交媒体 App": "Social Media App",
	"巴别塔 App": "Babel Tower App",
	"信号商店": "Signal Store",
	"笔记本 App": "Notebook App",
	"结束": "Finish",
	"继续交谈": "Continue Talking",
	"梗库": "Meme Bank",
	"MEME RING  /  拖拽移动": "MEME RING  /  DRAG TO MOVE",
	"还没有完整梗": "No completed memes yet",
	"进入第一天": "Enter Day One",
	"继续": "Continue",
	"污染 %d%%": "CORRUPTION %d%%",
	"资金 %d": "FUNDS %d",
	"塔层 1/5": "FLOOR 1/5",
	"今日行动\n%s": "TODAY'S ACTIONS\n%s",
	"DAY %d. %s\n路面在脚下滑动。手机 App 的窗口浮在屏幕旁边。": "DAY %d. %s\nThe street slides beneath your feet. App windows hover beside your phone.",
	"F  拾取 · %s\n%s": "F  PICK UP · %s\n%s",
	"交易": "Trade",
	"交谈": "Talk",
	"F  %s · %s": "F  %s · %s",

	# Babel app.
	"第 %d 层 / %d": "FLOOR %d / %d",
	"下一门槛：%d": "NEXT THRESHOLD: %d",
	"第 %d 层塔罗 / 三选一": "FLOOR %d TAROT / CHOOSE ONE OF THREE",
	"未命名塔罗": "Unnamed Tarot",
	"选择塔罗不消耗今日行动；特定牌组会自动形成组合被动。": "Choosing a tarot card does not use an action. Certain sets automatically form combo passives.",
	"已保留塔罗": "Kept Tarot Cards",
	"塔罗": "Tarot",
	"组合被动": "Combo Passives",
	"组合": "Combo",
	"遗产规则": "Legacy Rules",
	"还没有上一层语言留下来。": "No language has been left behind by an earlier floor yet.",
	"第 %d 层：%s": "FLOOR %d: %s",

	# Social navigation and common states.
	"关注": "Follow",
	"关注流": "Following",
	"发现": "Discover",
	"塔下": "Tower Base",
	"附近": "Nearby",
	"无法定位": "Location Unavailable",
	"设备保持无信号。附近内容无法取得位置。": "The device has no signal. Nearby posts cannot determine your location.",
	"还没有关注": "Not Following Anyone Yet",
	"在发现瀑布流里关注一个账号，它的帖子会留在这里。": "Follow an account in Discover and its posts will stay here.",
	"已关注": "Following",
	"继续下滑浏览更多信号": "Keep scrolling for more signals",
	"空位图像": "Empty-Seat Image",
	"塔下笔记": "Notes from the Tower Base",
	"哈吉米\nECHO": "HAJIMI\nECHO",
	"未命名信号": "Untitled Signal",
	"塔层 %d/%d": "FLOOR %d/%d",
	"信号档案": "Signal Archive",
	"信号偏向 / %s · %s   稀有度 %d": "SIGNAL TRAIT / %s · %s   RARITY %d",
	"无": "None",
	"今天没有可拾取的字": "No words can be collected today",

	# The twelve social post cards and their collectible words.
	"旧教学楼昨晚多出一层": "The Old School Building Gained an Extra Floor Last Night",
	"塔下施工档案": "Tower Base Construction Archive",
	"实拍：封闭的教学楼昨晚多出一层，末班电梯停在那里。": "Footage: The sealed school building gained an extra floor last night. The final elevator stopped there.",
	"空层底稿": "Empty-Floor Draft",
	"传播基础 +4": "Base reach +4",
	"不存在的十三层": "The Nonexistent Thirteenth Floor",
	"末班电梯": "The Final Elevator",
	"还在施工": "Still Under Construction",
	"无信号时收到明天短信": "A Text from Tomorrow Arrived While I Was Offline",
	"无信号通勤": "No-Signal Commute",
	"求证：断网后，我收到明天的自己发来的哈吉米。": "Seeking confirmation: After going offline, I received a message saying 'Hajimi' from tomorrow's me.",
	"回拨共鸣": "Callback Resonance",
	"命中风向时传播基础 +10": "Match a trend: base reach +10",
	"自己发来的": "Sent by Myself",
	"哈吉米": "Hajimi",
	"塔下每晚少一个窗口": "One Window Disappears from the Tower Base Every Night",
	"塔下夜巡": "Tower Base Night Watch",
	"记录：塔下每到午夜，就少一扇亮着的窗。": "Log: Every midnight, one lit window disappears from the tower base.",
	"熄灯增益": "Lights-Out Bonus",
	"污染达到 40% 时基础 +8": "At 40% corruption or higher, base reach +8",
	"每到午夜": "Every Midnight",
	"少一扇窗": "One Less Window",
	"照片里月亮多了一颗": "There Is an Extra Moon in the Photo",
	"夜空误差簿": "Night-Sky Error Log",
	"对照：昨晚的照片里，月亮比现实多一颗。": "Comparison: Last night's photo has one more moon than reality.",
	"月相缓冲": "Moonphase Buffer",
	"忽略 1 次复读扣减": "Ignore 1 repeat penalty",
	"多一颗月亮": "One Extra Moon",
	"比现实更多": "More than Reality",
	"昨晚的照片": "Last Night's Photo",
	"最后一班车没有终点": "The Last Bus Has No Terminus",
	"末班路线图": "Last-Run Route Map",
	"旧帖：最后一班车从来没有终点站。": "Old post: The last bus has never had a terminus.",
	"末班底稿": "Last-Run Draft",
	"传播基础 +5": "Base reach +5",
	"最后一班车": "The Last Bus",
	"没有终点": "No Terminus",
	"旧帖": "Old Post",
	"停电后广播喊了我名字": "The Radio Called My Name After the Blackout",
	"废站收音机": "Abandoned-Station Radio",
	"录音：停电以后，废站广播准时报站，然后叫了我的名字。": "Recording: After the blackout, the abandoned-station PA announced the stops on schedule, then called my name.",
	"广播共鸣": "Broadcast Resonance",
	"命中风向时传播基础 +8": "Match a trend: base reach +8",
	"停电以后": "After the Blackout",
	"广播喊我名字": "The Radio Called My Name",
	"废站": "Abandoned Station",
	"废站台昨晚重新亮灯": "The Abandoned Platform Lit Up Again Last Night",
	"封站观察员": "Closed-Station Observer",
	"目击：封了十年的站台，昨晚重新亮灯。": "Eyewitness: The platform, closed for ten years, lit up again last night.",
	"重启增益": "Reactivation Bonus",
	"污染达到 40% 时基础 +10": "At 40% corruption or higher, base reach +10",
	"封了十年": "Closed for Ten Years",
	"重新亮灯": "Lit Up Again",
	"站台": "Platform",
	"便利店店员没有影子": "The Convenience-Store Clerk Has No Shadow",
	"凌晨便利店": "Midnight Convenience Store",
	"路过：店整夜开着，店员却没有影子。": "Passing by: The store stayed open all night, but the clerk had no shadow.",
	"无影缓冲": "Shadowless Buffer",
	"整夜开着": "Open All Night",
	"没有影子": "No Shadow",
	"店员": "Clerk",
	"小区群里出现不存在的住户": "A Resident Who Does Not Exist Appeared in the Neighborhood Chat",
	"明日群公告": "Tomorrow's Group Notice",
	"截图：小区群凌晨多出一个查不到门牌的住户，还发来明天的失踪通知。": "Screenshot: At midnight, a resident with no traceable unit number appeared in the neighborhood chat and sent a missing-person notice dated tomorrow.",
	"明日底稿": "Tomorrow Draft",
	"传播基础 +6": "Base reach +6",
	"明天的通知": "Tomorrow's Notice",
	"失踪": "Missing",
	"小区群": "Neighborhood Chat",
	"十年前旧帖今天回复我": "A Ten-Year-Old Post Replied to Me Today",
	"旧帖考古队": "Old-Post Archaeology Team",
	"考古：十年前的旧帖今天突然回复我，头像是现在的我。": "Archive dig: A post from ten years ago suddenly replied to me today. Its avatar is me as I am now.",
	"旧帖共鸣": "Archive Resonance",
	"命中风向时传播基础 +12": "Match a trend: base reach +12",
	"十年前的旧帖": "A Ten-Year-Old Post",
	"今天的我": "Me Today",
	"考古": "Archive Dig",
	"地图上少了一条回家路": "The Map Is Missing One Road Home",
	"绿色路线图": "Green Route Map",
	"更新：地图删掉了我每天回家的那条路。": "Update: The map deleted the road I take home every day.",
	"迷路增益": "Lost-Road Bonus",
	"地图删掉了": "Deleted from the Map",
	"回家的路": "The Road Home",
	"这条小路": "This Side Road",
	"门禁说我没回家我却在屋里": "Access Control Says I Never Came Home, but I Am Inside",
	"门禁空号": "No-Number Access Log",
	"记录：门禁说我没回来，可我一直在屋里。": "Log: Access control says I never returned, but I have been inside the whole time.",
	"门禁缓冲": "Access Buffer",
	"我没回来": "I Never Came Back",
	"一直在屋里": "Inside the Whole Time",
	"门禁记录": "Access Log",

	# Social publishing and profile.
	"发布新信号": "Post a New Signal",
	"01  /  内容": "01  /  CONTENT",
	"拖拽或点击": "Drag or click",
	"从梗库放入一条完整表达": "Add a complete expression from the Meme Bank",
	"02  /  传播预估": "02  /  ESTIMATED REACH",
	"03  /  今日牌型": "03  /  TODAY'S PATTERN",
	"未命名牌型": "Unnamed Pattern",
	"确认发布消耗 1 次行动；预览与拖拽不扣行动。": "Posting uses 1 action. Previewing and dragging use none.",
	"确认发布": "Post",
	"我的": "Profile",
	"已合成梗：%d": "CRAFTED MEMES: %d",
	"污染：%d%%": "CORRUPTION: %d%%",
	"你的语言档案会随着塔层上升变窄。": "Your language archive narrows as you climb the tower.",
	"旧站镜像 / CACHE_%02d": "OLD-SITE MIRROR / CACHE_%02d",
	"[UNDER CONSTRUCTION / 请勿在午夜刷新]": "[UNDER CONSTRUCTION / DO NOT REFRESH AT MIDNIGHT]",
	"访客 %s  ·  最后更新 1998-13-05": "VISITOR %s  ·  LAST UPDATE 1998-13-05",
	"访客簿": "Guestbook",
	"镜像": "Mirrors",
	"源码": "Source",
	"这个网站比巴别塔早七年上线。所有日期都写着明天。": "This website went online seven years before the Babel Tower. Every date says tomorrow.",
	"站长留言：如果你能看见这行，说明你的楼层已经被缓存。": "Webmaster: If you can read this line, your floor has already been cached.",
	"访客 013：我没有留下名字，但名字已经显示在上面。": "Visitor 013: I left no name, but it was already displayed above.",
	"访客 005：第五层没有页面，只有返回上一页。": "Visitor 005: The fifth floor has no page, only Back.",
	"镜像 A / 校舍十三层 / 状态：仍在施工": "MIRROR A / SCHOOL FLOOR 13 / STATUS: STILL UNDER CONSTRUCTION",
	"镜像 B / 无信号短信 / 时间戳：明日": "MIRROR B / NO-SIGNAL MESSAGE / TIMESTAMP: TOMORROW",
	"镜像 C / 塔顶直播 / 观众：0": "MIRROR C / TOWER-TOP STREAM / VIEWERS: 0",
	"查看网页源代码": "View Page Source",
	"输入四位缓存编号": "Enter four-digit cache ID",
	"校验": "Verify",
	"缓存编号错误。服务器把你的输入记成了访客名。": "Wrong cache ID. The server recorded your entry as a visitor name.",
	"缓存 1305 已解锁": "CACHE 1305 UNLOCKED",
	"原始记录：塔并不是向上建造的。每次有人重复一句话，地面就向下退一层。所谓登顶，只是所有旧页面都停止回应。": "Original record: The tower was not built upward. Each time someone repeats a sentence, the ground recedes by one floor. Reaching the top only means every old page has stopped responding.",
	"断链：/tower/floor/13/index.htm": "BROKEN LINK: /tower/floor/13/index.htm",
	"浏览旧站不消耗今日行动。": "Browsing the old site does not use today's actions.",
	"首页": "Home",
	"发布": "Post",
	"已关注 @%s。": "Followed @%s.",
	"已取消关注 @%s。": "Unfollowed @%s.",
	"已保存这条信号。": "Signal saved.",
	"已取消保存。": "Signal removed from saved posts.",

	# Shop and notebook.
	"梗框 / MEME FRAME": "MEME FRAME",
	"持有 %d": "OWNED %d",
	"今天货架是空的。梗框每隔两天才补一次。": "The shelf is empty today. Meme Frames are restocked every other day.",
	"一个空框。只够装下一个字。": "An empty frame with room for just one word.",
	"购买后去笔记本，把拾到的单字拖进去。": "After buying it, open the Notebook and drag a collected word into it.",
	"已售出": "Sold",
	"购买梗框  %d 热币": "BUY MEME FRAME  %d HEAT COINS",
	"梗框造梗": "Frame Crafting",
	"双梗融合": "Meme Fusion",
	"确认融合": "Fuse",
	"装入梗框": "Place in Frame",
	"拾取字": "Collected Words",
	"来源被动": "Source Passive",
	"单字成梗  /  梗框 %d": "ONE-WORD MEME  /  FRAMES %d",
	"来源被动 / %s": "SOURCE PASSIVE / %s",
	"预览：%s": "PREVIEW: %s",
	"旧梗融合": "Existing Meme Fusion",
	"用滚轮或双指滑动右侧梗环挑选完整梗，再拖入两个槽位；也可以点击梗后再点槽位。": "Scroll or swipe with two fingers on the Meme Ring to choose completed memes, then drag them into both slots. You can also click a meme and then a slot.",
	"融合会保留两侧隐藏标签，并提高污染与传播倍率。": "Fusion preserves both memes' hidden tags and increases corruption and the reach multiplier.",
	"等待一个字": "Waiting for a word",
	"旧梗 A": "MEME A",
	"旧梗 B": "MEME B",
	"完整梗": "Completed Meme",
	"等待完整梗": "Waiting for a completed meme",
	"复合梗": "Fused Meme",

	# Publish breakdown and Meme Ring.
	"发布空格：%s": "POST SLOT: %s",
	"传播基础  --\n整数倍率  ×--\n倍率来源  --\n预计传播  --": "BASE REACH  --\nMULTIPLIER  ×--\nMULTIPLIER SOURCES  --\nESTIMATED REACH  --",
	"预计传播": "ESTIMATED REACH",
	"本次传播": "REACH THIS POST",
	"牌型 +%d": "Pattern +%d",
	"融合 +%d": "Fusion +%d",
	"遗物 +%d": "Relic +%d",
	"风向 +%d": "Trends +%d",
	"污染 +%d": "Corruption +%d",
	"复读 -%d": "Repeat -%d",
	"\n附加规则  %s": "\nADDITIONAL RULES  %s",
	"\n街区遗物  %s": "\nSTREET RELICS  %s",
	"传播基础  %d%s\n整数倍率  ×%d\n倍率来源  %s%s%s\n%s  %d": "BASE REACH  %d%s\nMULTIPLIER  ×%d\nMULTIPLIER SOURCES  %s%s%s\n%s  %d",
	"等待组牌": "Waiting for a pattern",
	"牌型成立": "Pattern complete",
	"尚未成立": "Not complete",
	"尚未放入完整梗": "No completed meme placed yet",
	"等待今日信号": "Waiting for today's signal",
	"%s\n%s  /  奖励：基础 +%d  ·  倍率 +%d  ·  污染 +%d": "%s\n%s  /  REWARD: BASE +%d  ·  MULTIPLIER +%d  ·  CORRUPTION +%d",
	"收起\n梗环": "CLOSE\nMEME RING",
	"梗库\n%d": "MEME BANK\n%d",
	"还没有完整梗。": "No completed memes yet.",
	"%02d / %02d\n%s": "%02d / %02d\n%s",

	# Reality UI and generated floor names.
	"离开": "Leave",
	"沟通辅助  %s": "COMMUNICATION AID  %s",
	"%s · %d 次\n%s": "%s · %d USES\n%s",
	"沟通辅助": "Communication Aid",
	"已购": "Purchased",
	"%d 资金": "%d FUNDS",
	"回应": "Respond",
	"任意键  %d / %d": "ANY KEY  %d / %d",
	"放下手机": "Lower Phone",
	"拿起手机": "Raise Phone",
	"街区遗物": "Street Relic",
	"信号已经写入。": "The signal has been recorded.",
	"对方": "Someone",
	"信号筹码": "Signal Token",
	"下一次发布的传播基础 +8。": "Next post: base reach +8.",
	"回声镜片": "Echo Lens",
	"下一次发布的整数倍率 +1。": "Next post: multiplier +1.",
	"清晰线": "Clarity Thread",
	"立即恢复 7 点清晰。": "Restore 7 Clarity immediately.",
	"信号商人": "Signal Merchant",
	"迟到者": "Latecomer",
	"回声住户": "Echo Resident",
	"抄写员": "Copyist",
	"无名信徒": "Nameless Believer",
	"旧帖目击者": "Old-Post Witness",
	"买到%s。": "Bought %s.",
	"这件沟通辅助没有成交。": "The communication aid was not purchased.",

	# Logs, action feedback, day changes, flashback, and ending.
	"你低头，手机边框从视野下方亮起来。": "You look down as the frame of your phone lights up from the bottom of your view.",
	"你回到离开时的位置。": "You return to where you left off.",
	"你放下手机，大街重新获得纵深。": "You lower the phone, and the street regains its depth.",
	"你又低头看向手机。": "You look down at your phone again.",
	"你停在%s面前。": "You stop in front of %s.",
	"梗仓库只在社交发布页出现。": "The Meme Bank is only available on the social posting screen.",
	"关闭 %s 窗口。": "Closed the %s window.",
	"展开手机主页。": "Opened the phone home screen.",
	"关闭社交详情。": "Closed the signal details.",
	"打开 %s。": "Opened %s.",
	"拾取：%s": "Collected: %s",
	"这个词没有进入笔记本。": "That word was not added to the Notebook.",
	"购买梗框：现在可以装入一个字。": "Meme Frame purchased. It can now hold one word.",
	"梗框没有成交。": "The Meme Frame was not purchased.",
	"塔罗已写入本层。组合条件会自动结算。": "The tarot card has been recorded on this floor. Combo conditions resolve automatically.",
	"这项许可已经关闭。": "This permit is no longer available.",
	"选中词语。": "Word selected.",
	"词语已拖入槽位。": "Word dragged into the slot.",
	"先选一个词语。": "Select a word first.",
	"词语已放入槽位。": "Word placed in the slot.",
	"单字进入梗框：%s": "Word placed in Meme Frame: %s",
	"需要一个梗框和一个拾取字。": "You need a Meme Frame and one collected word.",
	"旧梗已放入融合槽。": "Existing meme placed in the fusion slot.",
	"两个融合槽必须放入不同的完整梗。": "The two fusion slots must contain different completed memes.",
	"先从融合列表选择一个完整梗。": "Select a completed meme from the fusion list first.",
	"两个融合槽不能使用同一个梗。": "The same meme cannot be used in both fusion slots.",
	"融合完成：%s": "Fusion complete: %s",
	"需要两个不同且尚未融合过的完整梗。": "You need two different completed memes that have not already been fused together.",
	"选中完整梗。": "Completed meme selected.",
	"空格还在等一个完整梗。": "The slot is still waiting for a completed meme.",
	"梗已经塞进手机发布空格。": "The meme has been placed in the phone's post slot.",
	"完整梗已拖进发布空格。": "Completed meme dragged into the post slot.",
	"句子发到手机里。热度在塔下回响。": "The sentence was posted. Its heat echoes beneath the tower.",
	"发布空格里还没有完整梗。": "There is no completed meme in the post slot yet.",
	"TODAY'S ACTIONS DEPLETED  /  楼层 %d": "TODAY'S ACTIONS DEPLETED  /  FLOOR %d",
	"NEXT SIGNAL ACQUIRED  /  楼层 %d": "NEXT SIGNAL ACQUIRED  /  FLOOR %d",
	"我想正常说话": "I WANT TO SPEAK NORMALLY",
	"必须进入句子": "MUST ENTER THE SENTENCE",
	"信号丢失": "SIGNAL LOST",
	"哈吉米    哈吉米    哈吉米": "HAJIMI    HAJIMI    HAJIMI",
	"必须进入句子\n必须进入句子\n必须进入句子": "MUST ENTER THE SENTENCE\nMUST ENTER THE SENTENCE\nMUST ENTER THE SENTENCE",
	"沉默": "Silence",
	"黑屏之后，已经是第二天。": "After the blackout, it is already the next day.",
	"塔顶没有人": "No One Is at the Top of the Tower",
	"你还能留下一个声音。": "You can still leave one voice behind.",
	"你最后说：\n\n%s\n\n发射机把这个声音送回楼下。\n没有人回答。也许所有人都已经同时说完了。\n（这算是语言结束了吗？）\n指示灯没有提供选项。": "Your final words are:\n\n%s\n\nThe transmitter sends this voice back down.\nNo one answers. Maybe everyone has already finished speaking at the same time.\n(Is this where language ends?)\nThe indicator light offers no options.",
	"关系残留 %d / 100  ·  %s": "RELATIONSHIP RESIDUE %d / 100  ·  %s",
	"重开": "Start Over",

	# Day-plan feed posts and reality encounters.
	"旧帖被顶上来": "An Old Post Resurfaces",
	"同学": "Classmate",
	"你刚才想说什么？": "What were you trying to say?",
	"有人说哈吉米只是一个打错的名字，但打错的人已经注销。": "Someone says Hajimi was only a mistyped name, but the person who mistyped it has deleted their account.",
	"打错的人已经注销": "The person who made the typo has deleted their account",
	"打错": "Mistyped",
	"课桌下的账号": "Account Under the Desk",
	"别急着懂。先把它转出去，懂会在后面补票。": "Don't rush to understand. Repost it first; understanding can pay the fare later.",
	"懂会在后面补票": "Understanding will pay the fare later",
	"懂": "Understand",
	"清晰": "Clarity",
	"沉默用户在线": "Silent User Online",
	"塔下信徒": "Believer Below the Tower",
	"你可以不用那些词，试着直接回答我。": "You don't have to use those words. Try answering me directly.",
	"那个沉默用户又在线了。在线本身就是发言。": "That silent user is online again. Being online is itself a statement.",
	"回声管理员": "Echo Moderator",
	"哈吉米没有解释，哈吉米只返回你发出去的形状。": "Hajimi does not explain. Hajimi only returns the shape you sent out.",
	"返回你发出去的形状": "Returns the shape you sent",
	"形状": "Shape",
	"第一层通知": "First-Floor Notice",
	"班里的转发者": "Class Reposter",
	"你在哪一层？别说塔内地址，说你自己的话。": "What floor are you on? Don't give me a tower address. Use your own words.",
	"塔讯快报": "Tower Signal Bulletin",
	"第一级台阶确认开放。请用更新后的句式进入。": "The first step is confirmed open. Please enter using the updated sentence form.",
	"更新后的句式": "Updated sentence form",
	"台阶": "Step",
	"朝圣二群": "Pilgrimage Group 2",
	"塔不是建筑。塔是大家同时把解释往上挂。": "The tower is not a building. It is everyone hanging their explanations upward at once.",
	"把解释往上挂": "Hang explanations upward",
	"往上挂": "Hang upward",
	"解释开始收费": "Explanations Now Cost Extra",
	"梗店店员": "Meme-Shop Clerk",
	"如果不用它，你还剩下什么表达？": "Without it, what do you still have left to say?",
	"付费问答残页": "Paid Q&A Fragment",
	"为什么智者不说话？你为什么需要他说话？": "Why doesn't the sage speak? Why do you need them to?",
	"为什么": "Why",
	"旧语言清仓": "Old-Language Clearance",
	"普通话库存不足，剩余词义按污染价处理。": "Ordinary speech is low in stock. Remaining meanings are priced by corruption.",
	"词义按污染价处理": "Meaning priced by corruption",
	"污染价": "Corruption price",
	"圣歌体扩散": "Hymnal Register Spreads",
	"楼梯口合唱者": "Stairwell Chorister",
	"你能把自己的问题说出来，而不是唱出来吗？": "Can you say your question in your own words instead of singing it?",
	"塔间合唱": "Inter-Tower Choir",
	"塔啊，请把所有人挂成同一个句子。": "O tower, hang everyone into the same sentence.",
	"挂成同一个句子": "Hang into the same sentence",
	"塔啊": "O Tower",
	"未命名小组": "Untitled Group",
	"哈吉米在副歌里出现三次，第四次必须空着。": "Hajimi appears three times in the refrain. The fourth must be left blank.",
	"第四次必须空着": "The fourth must be blank",
	"空着": "Blank",
	"没有人在顶上": "No One at the Top",
	"塔顶": "Tower Top",
	"塔顶直播": "Tower-Top Livestream",
	"直播间没有画面。弹幕说这就是画面。": "The livestream has no picture. The chat says this is the picture.",
	"这就是画面": "This is the picture",
	"没有画面": "No picture",
	"智者账号": "Sage Account",
	"该用户不存在。不存在是最后一次上线。": "This user does not exist. Nonexistence was their last login.",
	"不存在是最后一次上线": "Nonexistence was the last login",
	"不存在": "Does not exist",
	"无法写入存档：%s": "Unable to write save file: %s",
}


const JA: Dictionary = {
	# Main menu, settings, phone shell, and HUD.
	"继续游戏": "つづきから",
	"回到上次离开的位置": "前回の続きから再開",
	"暂无自动存档": "オートセーブがありません",
	"新游戏": "ニューゲーム",
	"退出游戏": "ゲームを終了",
	"语言": "言語",
	"选择语言  /  言語を選択  /  CHOOSE LANGUAGE": "言語を選択",
	"返回": "戻る",
	"设置": "設定",
	"音量": "音量",
	"开启 VHS 质感": "VHS エフェクトを有効化",
	"手动保存": "手動保存",
	"已保存当前进度与设置。": "現在の進行状況と設定を保存しました。",
	"保存失败，请检查本地写入权限。": "保存に失敗しました。ローカルの書き込み権限を確認してください。",
	"退回主画面": "メインメニューへ戻る",
	"无信号": "圏外",
	"选择一个窗口": "ウィンドウを選択",
	"塔\n楼层档案": "塔\n階層アーカイブ",
	"帖\n信号瀑布": "投稿\nシグナルフィード",
	"店\n梗框商店": "店\nミーム枠ショップ",
	"本\n语言工坊": "ノート\n言葉の工房",
	"每个 App 会在手机旁打开独立窗口。": "各アプリはスマートフォンの横に別ウィンドウで開きます。",
	"社交媒体 App": "ソーシャルメディア App",
	"巴别塔 App": "バベルの塔 App",
	"信号商店": "シグナルショップ",
	"笔记本 App": "ノート App",
	"结束": "終了",
	"继续交谈": "会話を続ける",
	"梗库": "ミーム庫",
	"MEME RING  /  拖拽移动": "MEME RING  /  ドラッグで移動",
	"还没有完整梗": "完成したミームはまだない",
	"进入第一天": "1日目へ",
	"继续": "続ける",
	"污染 %d%%": "汚染度 %d%%",
	"资金 %d": "資金 %d",
	"塔层 1/5": "階層 1/5",
	"今日行动\n%s": "本日の行動\n%s",
	"DAY %d. %s\n路面在脚下滑动。手机 App 的窗口浮在屏幕旁边。": "DAY %d. %s\n足元を通りが流れていく。スマートフォンの横には App のウィンドウが浮かんでいる。",
	"F  拾取 · %s\n%s": "F  拾う · %s\n%s",
	"交易": "取引",
	"交谈": "話す",
	"F  %s · %s": "F  %s · %s",

	# Babel app.
	"第 %d 层 / %d": "第 %d 階 / %d",
	"下一门槛：%d": "次の閾値：%d",
	"第 %d 层塔罗 / 三选一": "第 %d 階のタロット / 3枚から1枚選択",
	"未命名塔罗": "名称未設定のタロット",
	"选择塔罗不消耗今日行动；特定牌组会自动形成组合被动。": "タロットの選択では本日の行動を消費しません。特定の組み合わせは自動的にコンボパッシブになります。",
	"已保留塔罗": "保有タロット",
	"塔罗": "タロット",
	"组合被动": "コンボパッシブ",
	"组合": "コンボ",
	"遗产规则": "遺産ルール",
	"还没有上一层语言留下来。": "以前の階から残された言葉はまだない。",
	"第 %d 层：%s": "第 %d 階：%s",

	# Social navigation and common states.
	"关注": "フォロー",
	"关注流": "フォロー中",
	"发现": "おすすめ",
	"塔下": "塔のふもと",
	"附近": "近く",
	"无法定位": "位置情報を取得できません",
	"设备保持无信号。附近内容无法取得位置。": "端末は圏外のままです。付近の投稿は位置情報を取得できません。",
	"还没有关注": "フォロー中のアカウントはまだない",
	"在发现瀑布流里关注一个账号，它的帖子会留在这里。": "「見つける」でアカウントをフォローすると、その投稿がここに残ります。",
	"已关注": "フォロー中",
	"继续下滑浏览更多信号": "さらにスクロールしてシグナルを見る",
	"空位图像": "空席の画像",
	"塔下笔记": "塔のふもとノート",
	"哈吉米\nECHO": "ハジミ\nECHO",
	"未命名信号": "無題のシグナル",
	"塔层 %d/%d": "階層 %d/%d",
	"信号档案": "シグナルアーカイブ",
	"信号偏向 / %s · %s   稀有度 %d": "シグナル特性 / %s · %s   レア度 %d",
	"无": "なし",
	"今天没有可拾取的字": "今日は拾える言葉がない",

	# The twelve social post cards and their collectible words.
	"旧教学楼昨晚多出一层": "昨夜、旧校舎に新しい階が一つ現れた",
	"塔下施工档案": "塔下工事記録",
	"实拍：封闭的教学楼昨晚多出一层，末班电梯停在那里。": "実写：封鎖された校舎に昨夜、階が一つ増え、最終エレベーターはそこで止まった。",
	"空层底稿": "空階の下書き",
	"传播基础 +4": "基礎拡散力 +4",
	"不存在的十三层": "存在しない13階",
	"末班电梯": "最終エレベーター",
	"还在施工": "まだ工事中",
	"无信号时收到明天短信": "圏外なのに、明日の自分からメッセージが届いた",
	"无信号通勤": "圏外通勤",
	"求证：断网后，我收到明天的自己发来的哈吉米。": "検証求む：通信が切れたあと、明日の自分から「ハジミ」とメッセージが届いた。",
	"回拨共鸣": "折り返し共鳴",
	"命中风向时传播基础 +10": "トレンド一致時、基礎拡散力 +10",
	"自己发来的": "自分から届いた",
	"哈吉米": "ハジミ",
	"塔下每晚少一个窗口": "塔のふもとでは毎晩、窓が一つ消える",
	"塔下夜巡": "塔下夜間巡回",
	"记录：塔下每到午夜，就少一扇亮着的窗。": "記録：塔下では真夜中になるたび、明かりのついた窓が一つ減る。",
	"熄灯增益": "消灯ボーナス",
	"污染达到 40% 时基础 +8": "汚染度40%以上で基礎拡散力 +8",
	"每到午夜": "真夜中になるたび",
	"少一扇窗": "窓が一つ減る",
	"照片里月亮多了一颗": "写真に月がもう一つ写っている",
	"夜空误差簿": "夜空誤差記録",
	"对照：昨晚的照片里，月亮比现实多一颗。": "比較：昨夜の写真には、現実より月が一つ多く写っている。",
	"月相缓冲": "月相バッファ",
	"忽略 1 次复读扣减": "反復ペナルティを1回無効化",
	"多一颗月亮": "月が一つ多い",
	"比现实更多": "現実より多い",
	"昨晚的照片": "昨夜の写真",
	"最后一班车没有终点": "最終バスに終点はない",
	"末班路线图": "最終便路線図",
	"旧帖：最后一班车从来没有终点站。": "旧投稿：最終バスには最初から終点がない。",
	"末班底稿": "最終便の下書き",
	"传播基础 +5": "基礎拡散力 +5",
	"最后一班车": "最終バス",
	"没有终点": "終点がない",
	"旧帖": "旧投稿",
	"停电后广播喊了我名字": "停電後、放送が私の名前を呼んだ",
	"废站收音机": "廃駅ラジオ",
	"录音：停电以后，废站广播准时报站，然后叫了我的名字。": "録音：停電後、廃駅の放送は時刻どおりに駅名を告げ、それから私の名前を呼んだ。",
	"广播共鸣": "放送共鳴",
	"命中风向时传播基础 +8": "トレンド一致時、基礎拡散力 +8",
	"停电以后": "停電後",
	"广播喊我名字": "放送が私の名前を呼ぶ",
	"废站": "廃駅",
	"废站台昨晚重新亮灯": "廃ホームに昨夜、再び明かりがついた",
	"封站观察员": "封鎖駅監視員",
	"目击：封了十年的站台，昨晚重新亮灯。": "目撃：10年間封鎖されていたホームに、昨夜再び明かりがついた。",
	"重启增益": "再起動ボーナス",
	"污染达到 40% 时基础 +10": "汚染度40%以上で基礎拡散力 +10",
	"封了十年": "10年間封鎖",
	"重新亮灯": "再び点灯",
	"站台": "ホーム",
	"便利店店员没有影子": "コンビニ店員に影がない",
	"凌晨便利店": "深夜コンビニ",
	"路过：店整夜开着，店员却没有影子。": "通りすがり：店は一晩中開いていたが、店員には影がなかった。",
	"无影缓冲": "影なしバッファ",
	"整夜开着": "一晩中営業",
	"没有影子": "影がない",
	"店员": "店員",
	"小区群里出现不存在的住户": "団地チャットに存在しない住人が現れた",
	"明日群公告": "明日のグループ通知",
	"截图：小区群凌晨多出一个查不到门牌的住户，还发来明天的失踪通知。": "スクリーンショット：深夜の団地チャットに部屋番号を確認できない住人が現れ、明日付けの失踪通知を送ってきた。",
	"明日底稿": "明日の下書き",
	"传播基础 +6": "基礎拡散力 +6",
	"明天的通知": "明日の通知",
	"失踪": "失踪",
	"小区群": "団地チャット",
	"十年前旧帖今天回复我": "10年前の旧投稿が今日、私に返信した",
	"旧帖考古队": "旧投稿発掘隊",
	"考古：十年前的旧帖今天突然回复我，头像是现在的我。": "発掘：10年前の旧投稿が今日突然返信してきた。アイコンは今の私だ。",
	"旧帖共鸣": "旧投稿共鳴",
	"命中风向时传播基础 +12": "トレンド一致時、基礎拡散力 +12",
	"十年前的旧帖": "10年前の旧投稿",
	"今天的我": "今日の私",
	"考古": "発掘",
	"地图上少了一条回家路": "地図から帰り道が一本消えた",
	"绿色路线图": "緑のルートマップ",
	"更新：地图删掉了我每天回家的那条路。": "更新：地図から、毎日使っていた帰り道が削除された。",
	"迷路增益": "迷子ボーナス",
	"地图删掉了": "地図から削除された",
	"回家的路": "帰り道",
	"这条小路": "この小道",
	"门禁说我没回家我却在屋里": "入退室記録では未帰宅なのに、私は部屋にいる",
	"门禁空号": "空番号の入退室記録",
	"记录：门禁说我没回来，可我一直在屋里。": "記録：入退室記録では私は戻っていないことになっているが、ずっと部屋にいた。",
	"门禁缓冲": "入退室バッファ",
	"我没回来": "私は戻っていない",
	"一直在屋里": "ずっと部屋にいた",
	"门禁记录": "入退室記録",

	# Social publishing and profile.
	"发布新信号": "新しいシグナルを投稿",
	"01  /  内容": "01  /  内容",
	"拖拽或点击": "ドラッグまたはクリック",
	"从梗库放入一条完整表达": "ミーム庫から完成した表現を入れる",
	"02  /  传播预估": "02  /  予想拡散",
	"03  /  今日牌型": "03  /  本日のパターン",
	"未命名牌型": "名称未設定のパターン",
	"确认发布消耗 1 次行动；预览与拖拽不扣行动。": "投稿すると行動を1回消費します。プレビューとドラッグでは消費しません。",
	"确认发布": "投稿する",
	"我的": "プロフィール",
	"已合成梗：%d": "作成済みミーム：%d",
	"污染：%d%%": "汚染度：%d%%",
	"你的语言档案会随着塔层上升变窄。": "塔を上るほど、あなたの言語アーカイブは狭くなっていく。",
	"旧站镜像 / CACHE_%02d": "旧サイト・ミラー / CACHE_%02d",
	"[UNDER CONSTRUCTION / 请勿在午夜刷新]": "[UNDER CONSTRUCTION / 深夜0時に更新しないでください]",
	"访客 %s  ·  最后更新 1998-13-05": "訪問者 %s  ·  最終更新 1998-13-05",
	"访客簿": "ゲストブック",
	"镜像": "ミラー",
	"源码": "ソース",
	"这个网站比巴别塔早七年上线。所有日期都写着明天。": "このサイトはバベル塔より七年早く公開された。日付はすべて「明日」になっている。",
	"站长留言：如果你能看见这行，说明你的楼层已经被缓存。": "管理人：この行が見えるなら、あなたの階層はすでにキャッシュされている。",
	"访客 013：我没有留下名字，但名字已经显示在上面。": "訪問者013：名前は残していない。それなのに、上にはもう表示されている。",
	"访客 005：第五层没有页面，只有返回上一页。": "訪問者005：五階にはページがない。「戻る」だけがある。",
	"镜像 A / 校舍十三层 / 状态：仍在施工": "ミラーA / 校舎13階 / 状態：工事継続中",
	"镜像 B / 无信号短信 / 时间戳：明日": "ミラーB / 圏外メッセージ / タイムスタンプ：明日",
	"镜像 C / 塔顶直播 / 观众：0": "ミラーC / 塔頂ライブ / 視聴者：0",
	"查看网页源代码": "ページのソースを表示",
	"输入四位缓存编号": "4桁のキャッシュ番号を入力",
	"校验": "照合",
	"缓存编号错误。服务器把你的输入记成了访客名。": "キャッシュ番号が違います。サーバーは入力内容を訪問者名として記録しました。",
	"缓存 1305 已解锁": "キャッシュ1305を解放しました",
	"原始记录：塔并不是向上建造的。每次有人重复一句话，地面就向下退一层。所谓登顶，只是所有旧页面都停止回应。": "原記録：塔は上へ建てられたのではない。誰かが同じ文を繰り返すたび、地面が一階ぶん下がっていく。頂上に着くとは、古いページがすべて応答をやめることにすぎない。",
	"断链：/tower/floor/13/index.htm": "リンク切れ：/tower/floor/13/index.htm",
	"浏览旧站不消耗今日行动。": "旧サイトの閲覧では本日の行動を消費しません。",
	"首页": "ホーム",
	"发布": "投稿",
	"已关注 @%s。": "@%sをフォローした。",
	"已取消关注 @%s。": "@%sのフォローを解除した。",
	"已保存这条信号。": "このシグナルを保存した。",
	"已取消保存。": "保存を解除した。",

	# Shop and notebook.
	"梗框 / MEME FRAME": "ミーム枠 / MEME FRAME",
	"持有 %d": "所持数 %d",
	"今天货架是空的。梗框每隔两天才补一次。": "今日は棚が空だ。ミーム枠は2日おきに補充される。",
	"一个空框。只够装下一个字。": "空の枠。一文字だけ入れられる。",
	"购买后去笔记本，把拾到的单字拖进去。": "購入後、ノートを開いて拾った言葉をドラッグしてください。",
	"已售出": "売り切れ",
	"购买梗框  %d 热币": "ミーム枠を購入  %d ヒートコイン",
	"梗框造梗": "ミーム枠で作成",
	"双梗融合": "ミーム融合",
	"确认融合": "融合する",
	"装入梗框": "ミーム枠に入れる",
	"拾取字": "拾った言葉",
	"来源被动": "出典パッシブ",
	"单字成梗  /  梗框 %d": "一語ミーム  /  ミーム枠 %d",
	"来源被动 / %s": "出典パッシブ / %s",
	"预览：%s": "プレビュー：%s",
	"旧梗融合": "既存ミーム融合",
	"用滚轮或双指滑动右侧梗环挑选完整梗，再拖入两个槽位；也可以点击梗后再点槽位。": "右側のミームリングをホイールまたは二本指で動かして完成済みミームを選び、二つのスロットへドラッグします。ミームをクリックしてからスロットを選ぶこともできます。",
	"融合会保留两侧隐藏标签，并提高污染与传播倍率。": "融合すると両方の隠しタグが残り、汚染度と拡散倍率が上がります。",
	"等待一个字": "言葉を待っています",
	"旧梗 A": "ミーム A",
	"旧梗 B": "ミーム B",
	"完整梗": "完成済みミーム",
	"等待完整梗": "完成済みミームを待っています",
	"复合梗": "融合ミーム",

	# Publish breakdown and Meme Ring.
	"发布空格：%s": "投稿スロット：%s",
	"传播基础  --\n整数倍率  ×--\n倍率来源  --\n预计传播  --": "基礎拡散力  --\n倍率  ×--\n倍率の内訳  --\n予想拡散  --",
	"预计传播": "予想拡散",
	"本次传播": "今回の拡散",
	"牌型 +%d": "パターン +%d",
	"融合 +%d": "融合 +%d",
	"遗物 +%d": "遺物 +%d",
	"风向 +%d": "トレンド +%d",
	"污染 +%d": "汚染度 +%d",
	"复读 -%d": "反復 -%d",
	"\n附加规则  %s": "\n追加ルール  %s",
	"\n街区遗物  %s": "\n街区の遺物  %s",
	"传播基础  %d%s\n整数倍率  ×%d\n倍率来源  %s%s%s\n%s  %d": "基礎拡散力  %d%s\n倍率  ×%d\n倍率の内訳  %s%s%s\n%s  %d",
	"等待组牌": "パターン待ち",
	"牌型成立": "パターン成立",
	"尚未成立": "未成立",
	"尚未放入完整梗": "完成済みミームがまだ置かれていない",
	"等待今日信号": "本日のシグナル待ち",
	"%s\n%s  /  奖励：基础 +%d  ·  倍率 +%d  ·  污染 +%d": "%s\n%s  /  報酬：基礎 +%d  ·  倍率 +%d  ·  汚染度 +%d",
	"收起\n梗环": "閉じる\nミームリング",
	"梗库\n%d": "ミーム庫\n%d",
	"还没有完整梗。": "完成したミームはまだない。",
	"%02d / %02d\n%s": "%02d / %02d\n%s",

	# Reality UI and generated floor names.
	"离开": "離れる",
	"沟通辅助  %s": "会話補助  %s",
	"%s · %d 次\n%s": "%s · %d 回\n%s",
	"沟通辅助": "会話補助",
	"已购": "購入済み",
	"%d 资金": "%d 資金",
	"回应": "応答",
	"任意键  %d / %d": "何かキーを押す  %d / %d",
	"放下手机": "スマートフォンを下ろす",
	"拿起手机": "スマートフォンを持ち上げる",
	"街区遗物": "街区の遺物",
	"信号已经写入。": "シグナルが記録された。",
	"对方": "相手",
	"信号筹码": "シグナル・トークン",
	"下一次发布的传播基础 +8。": "次の投稿：基礎拡散力 +8。",
	"回声镜片": "こだまのレンズ",
	"下一次发布的整数倍率 +1。": "次の投稿：倍率 +1。",
	"清晰线": "明晰の糸",
	"立即恢复 7 点清晰。": "明晰度を7回復する。",
	"信号商人": "シグナル商人",
	"迟到者": "遅刻者",
	"回声住户": "こだまの住人",
	"抄写员": "写字係",
	"无名信徒": "名もなき信徒",
	"旧帖目击者": "旧投稿の目撃者",
	"买到%s。": "%sを買った。",
	"这件沟通辅助没有成交。": "この会話補助は購入できなかった。",

	# Logs, action feedback, day changes, flashback, and ending.
	"你低头，手机边框从视野下方亮起来。": "視線を落とすと、視界の下からスマートフォンの縁が明るく浮かび上がる。",
	"你回到离开时的位置。": "離れたときの場所に戻った。",
	"你放下手机，大街重新获得纵深。": "スマートフォンを下ろすと、通りに奥行きが戻る。",
	"你又低头看向手机。": "もう一度スマートフォンに目を落とす。",
	"你停在%s面前。": "%sの前で足を止めた。",
	"梗仓库只在社交发布页出现。": "ミーム庫はソーシャル投稿画面でのみ開けます。",
	"关闭 %s 窗口。": "%sウィンドウを閉じた。",
	"展开手机主页。": "スマートフォンのホーム画面を開いた。",
	"关闭社交详情。": "シグナルの詳細を閉じた。",
	"打开 %s。": "%sを開いた。",
	"拾取：%s": "拾得：%s",
	"这个词没有进入笔记本。": "その言葉はノートに入らなかった。",
	"购买梗框：现在可以装入一个字。": "ミーム枠を購入した。一文字を入れられる。",
	"梗框没有成交。": "ミーム枠は購入できなかった。",
	"塔罗已写入本层。组合条件会自动结算。": "タロットがこの階に記録された。コンボ条件は自動的に判定される。",
	"这项许可已经关闭。": "この許可はもう利用できない。",
	"选中词语。": "言葉を選択した。",
	"词语已拖入槽位。": "言葉をスロットへドラッグした。",
	"先选一个词语。": "先に言葉を選択してください。",
	"词语已放入槽位。": "言葉をスロットに入れた。",
	"单字进入梗框：%s": "言葉をミーム枠に入れた：%s",
	"需要一个梗框和一个拾取字。": "ミーム枠と拾った言葉が一つ必要です。",
	"旧梗已放入融合槽。": "既存ミームを融合スロットに入れた。",
	"两个融合槽必须放入不同的完整梗。": "二つの融合スロットには別々の完成済みミームが必要です。",
	"先从融合列表选择一个完整梗。": "先に融合リストから完成済みミームを選択してください。",
	"两个融合槽不能使用同一个梗。": "両方の融合スロットに同じミームは使えません。",
	"融合完成：%s": "融合完了：%s",
	"需要两个不同且尚未融合过的完整梗。": "まだ組み合わせていない、異なる完成済みミームが二つ必要です。",
	"选中完整梗。": "完成済みミームを選択した。",
	"空格还在等一个完整梗。": "スロットはまだ完成済みミームを待っている。",
	"梗已经塞进手机发布空格。": "ミームをスマートフォンの投稿スロットに入れた。",
	"完整梗已拖进发布空格。": "完成済みミームを投稿スロットへドラッグした。",
	"句子发到手机里。热度在塔下回响。": "文を投稿した。熱が塔下にこだまする。",
	"发布空格里还没有完整梗。": "投稿スロットに完成済みミームがまだない。",
	"TODAY'S ACTIONS DEPLETED  /  楼层 %d": "本日の行動を使い切った  /  第 %d 階",
	"NEXT SIGNAL ACQUIRED  /  楼层 %d": "次のシグナルを獲得  /  第 %d 階",
	"我想正常说话": "普通に話したい",
	"必须进入句子": "文に入らなければならない",
	"信号丢失": "シグナル消失",
	"哈吉米    哈吉米    哈吉米": "ハジミ    ハジミ    ハジミ",
	"必须进入句子\n必须进入句子\n必须进入句子": "文に入らなければならない\n文に入らなければならない\n文に入らなければならない",
	"沉默": "沈黙",
	"黑屏之后，已经是第二天。": "暗転のあと、すでに翌日になっていた。",
	"塔顶没有人": "塔の頂上には誰もいない",
	"你还能留下一个声音。": "まだ一つだけ、声を残せる。",
	"你最后说：\n\n%s\n\n发射机把这个声音送回楼下。\n没有人回答。也许所有人都已经同时说完了。\n（这算是语言结束了吗？）\n指示灯没有提供选项。": "あなたが最後に口にしたのは：\n\n%s\n\n送信機はその声を階下へ送り返す。\n誰も答えない。もしかすると、全員が同時に話し終えてしまったのかもしれない。\n（これが言葉の終わりなのだろうか？）\n表示灯は選択肢を示さない。",
	"关系残留 %d / 100  ·  %s": "関係の残滓 %d / 100  ·  %s",
	"重开": "最初から",

	# 日ごとの投稿と現実会話。
	"旧帖被顶上来": "過去ログが浮上",
	"同学": "クラスメイト",
	"你刚才想说什么？": "さっき、何を言おうとしたの？",
	"有人说哈吉米只是一个打错的名字，但打错的人已经注销。": "ハジミは単なる打ち間違いの名前だと言う人がいる。でも、打ち間違えた本人はもう退会している。",
	"打错的人已经注销": "打ち間違えた本人は退会済み",
	"打错": "打ち間違い",
	"课桌下的账号": "机の下のアカウント",
	"别急着懂。先把它转出去，懂会在后面补票。": "急いで理解しなくていい。先に拡散して。理解はあとから不足分を払う。",
	"懂会在后面补票": "理解はあとから不足分を払う",
	"懂": "理解",
	"清晰": "明晰",
	"沉默用户在线": "沈黙ユーザー、オンライン",
	"塔下信徒": "塔下の信徒",
	"你可以不用那些词，试着直接回答我。": "その言葉を使わなくてもいい。私に直接答えてみて。",
	"那个沉默用户又在线了。在线本身就是发言。": "あの沈黙ユーザーがまたオンラインになった。オンラインでいること自体が発言だ。",
	"回声管理员": "こだま管理人",
	"哈吉米没有解释，哈吉米只返回你发出去的形状。": "ハジミは説明しない。送り出した形だけを返してくる。",
	"返回你发出去的形状": "送り出した形を返す",
	"形状": "形",
	"第一层通知": "第一階層のお知らせ",
	"班里的转发者": "クラスの拡散係",
	"你在哪一层？别说塔内地址，说你自己的话。": "今、何階にいる？ 塔内の住所ではなく、自分の言葉で答えて。",
	"塔讯快报": "塔信速報",
	"第一级台阶确认开放。请用更新后的句式进入。": "第一段目の開放を確認。更新後の文型で入場してください。",
	"更新后的句式": "更新後の文型",
	"台阶": "段",
	"朝圣二群": "巡礼グループ2",
	"塔不是建筑。塔是大家同时把解释往上挂。": "塔は建物ではない。全員が同時に説明を上へ吊るしたものだ。",
	"把解释往上挂": "説明を上へ吊るす",
	"往上挂": "上へ吊るす",
	"解释开始收费": "説明、有料化",
	"梗店店员": "ミームショップ店員",
	"如果不用它，你还剩下什么表达？": "それを使わないなら、まだ何を表現できる？",
	"付费问答残页": "有料Q&Aの断片",
	"为什么智者不说话？你为什么需要他说话？": "なぜ賢者は話さない？ なぜ、あなたは賢者に話してほしい？",
	"为什么": "なぜ",
	"旧语言清仓": "旧言語クリアランス",
	"普通话库存不足，剩余词义按污染价处理。": "普通の言葉は在庫不足です。残りの意味は汚染価格で扱います。",
	"词义按污染价处理": "意味は汚染価格",
	"污染价": "汚染価格",
	"圣歌体扩散": "聖歌調、拡散中",
	"楼梯口合唱者": "階段口の合唱者",
	"你能把自己的问题说出来，而不是唱出来吗？": "自分の問いを、歌わずに話せる？",
	"塔间合唱": "塔間合唱",
	"塔啊，请把所有人挂成同一个句子。": "塔よ、全員を同じ文に吊るしてください。",
	"挂成同一个句子": "同じ文に吊るす",
	"塔啊": "塔よ",
	"未命名小组": "無名グループ",
	"哈吉米在副歌里出现三次，第四次必须空着。": "ハジミは副歌に三回現れる。四回目は空けなければならない。",
	"第四次必须空着": "四回目は空白",
	"空着": "空ける",
	"没有人在顶上": "頂上には誰もいない",
	"塔顶": "塔の頂上",
	"塔顶直播": "塔頂ライブ",
	"直播间没有画面。弹幕说这就是画面。": "配信には映像がない。コメント欄は、これが映像だと言う。",
	"这就是画面": "これが映像",
	"没有画面": "映像なし",
	"智者账号": "賢者のアカウント",
	"该用户不存在。不存在是最后一次上线。": "このユーザーは存在しない。存在しないことが最後のログインだった。",
	"不存在是最后一次上线": "存在しないことが最後のログイン",
	"不存在": "存在しない",
	"无法写入存档：%s": "セーブデータを書き込めません：%s",
}


static func entries(locale_code: String) -> Dictionary:
	match locale_code.to_lower():
		"en":
			return EN
		"ja":
			return JA
		_:
			return {}
